import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {webcrypto} from 'node:crypto';
import {applyMoves} from '../tools/apply-editor-moves.mjs';
const ctx=vm.createContext({crypto:webcrypto});
vm.runInContext(fs.readFileSync('js/audio-mix.js','utf8'),ctx);
const mix=ctx.EmberAudioMix;
let heard=0;mix.subscribe(()=>heard++);
mix.load({'sfx:door':.8});mix.set('sfx:door',.5);
assert.equal(mix.level('sfx:door'),.5);assert.equal(heard,2);
const ops=JSON.parse(JSON.stringify(mix.operations()));
assert.deepEqual(JSON.parse(JSON.stringify(mix.operations())),ops,'Repeated saves retain the same submission identity');
const revision='a'.repeat(64),draft={schema:1,id:webcrypto.randomUUID(),map:'world',sourceRevision:revision,operations:ops};
const first=applyMoves({schema:1,maps:{},audio:{'sfx:door':.8},applied:[]},draft,revision);
assert.equal(first.audio['sfx:door'],.5);assert.deepEqual(first.maps.world,{});
mix.sending(draft);mix.set('sfx:door',.6);mix.published(draft.id);
assert.equal(mix.level('sfx:door'),.6,'Publishing cannot discard a later live adjustment');
assert.equal(mix.operations()[0].before,.5);
const second=applyMoves(first,{...draft,id:webcrypto.randomUUID(),map:'tavern',operations:JSON.parse(JSON.stringify(mix.operations()))},revision);
assert.equal(second.audio['sfx:door'],.6,'Mixer settings are global across maps');
assert.throws(()=>applyMoves(second,{...draft,id:webcrypto.randomUUID()},revision),/newer submission/,'Out-of-order submissions cannot restore stale audio');
assert.throws(()=>applyMoves(second,{...draft,id:webcrypto.randomUUID(),operations:[{...ops[0],client:webcrypto.randomUUID()}]},revision),/newer submission/,'Concurrent editors cannot overwrite each other');
for(const op of [{...ops[0],value:9},{...ops[0],value:NaN},{...ops[0],key:'__proto__'}])assert.throws(()=>applyMoves(first,{...draft,id:webcrypto.randomUUID(),operations:[op]},revision),/Invalid audio/);
mix.reset();assert.equal(mix.level('sfx:door'),.5);assert.equal(mix.operations().length,0);
// Every player door path uses the same opening hook, including animated rooms.
let opens=0;const doorCtx=vm.createContext({window:{EmberSfx:{door:()=>opens++}},MD:{},P:{},MAPID:'world'});
const source=fs.readFileSync('js/generated/game-part-3.js','utf8');
vm.runInContext(source.slice(source.indexOf('function beginDoorEntry('),source.indexOf('\nfunction drawArena(')),doorCtx);
for(const d of [{to:'house'},{to:'tavern'},{to:'school',stairDown:true}])doorCtx.beginDoorEntry(d);
assert.equal(opens,3);
console.log('PASS: live mix changes, stable drafts, global publication, mid-publish changes, stale/conflicting submissions, validation, reset and all player door paths.');
