import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run}=await loadEditorGame(process.cwd(),{log(){},warn(){},error(){}});
await run('loadPublishedEditorLayouts()');
run(`window.LDRCoopRender={enable(){}};quest=Q.DONE;greenPhase='gone';bridgeCleared=true;guardsAside=true;dragonIntroDone=true;loadMap('world',true);P.x=776;P.y=6048;`);
await run(`LDRCampaign.start({uid:'host',players:[{uid:'host',id:'h',profile:{name:'Host',hair:'dark',eyes:'blue'}},{uid:'guest',id:'g',profile:{name:'Guest',hair:'dark',eyes:'blue'}}],onNotice:()=>{},onSave:()=>{}})`);
const data=s=>JSON.parse(run('JSON.stringify('+s+')'));
run(`scene=null;sayNpc=null;revealing=false;arenaLock=null;foes=[];LDRCampaign.withActor('host',()=>{P.x=700;P.y=6048;pHp=6;pInv=0;dragon.hp=20;});LDRCampaign.withActor('guest',()=>{P.x=900;P.y=6048;pHp=6;pInv=0;dragon.hp=20;});`);
run(`LDRCampaign.withActor('guest',()=>hurtPlayer(2));`);
assert.equal(data(`LDRCampaign.actor('host').vars.pHp`),6);assert.equal(data(`LDRCampaign.actor('guest').vars.pHp`),4);
run(`var f={x:902,y:6048,st:'walk'};var before=LDRCampaign.beginEnemy(f);hurtDragon(2);LDRCampaign.endEnemy(before);`);
assert.equal(data(`LDRCampaign.actor('host').dragon.hp`),20);assert.equal(data(`LDRCampaign.actor('guest').dragon.hp`),18);
assert.equal(data(`f.coopTarget`),'guest');
run(`before=LDRCampaign.beginProjectile({coopTarget:'host'});hurtDragon(1);LDRCampaign.endEnemy(before);`);
assert.equal(data(`LDRCampaign.actor('host').dragon.hp`),19);assert.equal(data(`LDRCampaign.actor('guest').dragon.hp`),18);
run(`LDRCampaign.withActor('guest',()=>{pInv=0;hurtPlayer(20);});showDeath();`);
assert.equal(data(`deadShown`),false,'A surviving partner prevents a party wipe');
run(`LDRCampaign.withActor('host',()=>{P.x=900;P.y=6058;});LDRCampaign.command('host','revive');`);
assert.equal(data(`LDRCampaign.actor('guest').vars.pHp`),3);
console.log('PASS: independent health, stable enemy/projectile ownership and partner revive.');
run(`LDRCampaign.withActor('host',()=>Crafting.giveKit());`);
assert.equal(run(`LDRCampaign.withActor('guest',()=>Crafting.hasKit())`),true);
run(`var node=Crafting.inspect().nodes.find(n=>n.id==='craft:intro:herb');LDRCampaign.withActor('host',()=>{P.x=node.x;P.y=node.y;P.act=null;});LDRCampaign.withActor('guest',()=>{P.x=node.x;P.y=node.y;P.act=null;});`);
assert.equal(run(`LDRCampaign.withActor('host',()=>Crafting.gather())`),true);
assert.equal(run(`LDRCampaign.withActor('guest',()=>Crafting.count('herb'))`),0);
assert.equal(run(`LDRCampaign.withActor('guest',()=>Crafting.gather())`),true);
assert.equal(run(`LDRCampaign.withActor('host',()=>Crafting.count('herb'))`),2);
assert.equal(run(`LDRCampaign.withActor('guest',()=>Crafting.count('herb'))`),2);
assert.equal(run(`LDRCampaign.withActor('guest',()=>Crafting.gather())`),false);
run(`charm.lamp=true;breathHas.ice=true;`);
assert.equal(run(`LDRCampaign.withActor('guest',()=>charm.lamp&&breathHas.ice)`),true);
console.log('PASS: personal collection at the same real world node; recipe, kit, story equipment and breath unlocks shared.');
run(`playScene(['Corin: A shared line.','Corin: A second line.']);typeAll();scene.t=1;`);
run(`LDRCampaign.command('host','action')`);assert.equal(run('scene.i'),0);
run(`LDRCampaign.command('guest','action')`);assert.equal(run('scene.i'),1);
run(`scene=null;sayNpc=null;revealing=false;sayOff();arenaLock=null;foes=[];`);
const saved=data(`LDRCampaign.checkpoint()`);assert(saved);assert.equal(saved.players.host.crafting.ingredients.herb,2);assert.equal(saved.players.guest.crafting.ingredients.herb,2);assert.equal(saved.players.guest.hp,3);assert(saved.save.charm.lamp);assert(saved.save.breathHas.ice);
assert(run(`EmberCloudSaveValid(${JSON.stringify(JSON.stringify({...saved.save,coop:{version:1,id:'test',players:saved.players}}))})`));
console.log('PASS: both riders must advance dialogue; safe checkpoint includes both inventories and health in the existing cloud-save format.');
// Boss projectiles retain the rider targeted at casting even when another rider
// becomes closer before impact. The real boss effect code runs once per tick.
await run('IceMoth.prepare()');
run(`scene=null;sayNpc=null;revealing=false;bossScene=null;ovl=null;ask=null;fadeDir=0;doorMotion=null;ride=null;foesHeld=false;devSafe=false;
window.EmberArenaEntry=undefined;window.EmberRiding=undefined;MD={...W.maps.world,pyramid:false,roomBlocks:[],collisionOverrides:{}};
MAPID='world';MW=3000;MH=600;PXW=MW*TS;PXH=MH*TS;solid=new Uint8Array(MW*MH);npcs=[];objs=[];fenceAt=null;
var moth={kind:'icemoth',x:2346*16+8,y:168*16+8,dir:'d',flip:false,_thinking:true,hold:0,st:'swing',t:.13,hit:0,mothAttack:'shards'};
arenaLock=IceMoth.arena;arenaT=1;foes=[moth];IceMoth.reset();
LDRCampaign.withActor('guest',()=>{P.x=moth.x;P.y=moth.y+40;pHp=6;pInv=0;mounted=false;dragon.on=false;glassShieldHeld=false;glassShield=false;moth.mothAim={x:P.x,y:P.y,dragon:false};IceMoth.step(moth,0);});
LDRCampaign.withActor('host',()=>{P.x=moth.x+24;P.y=moth.y;pHp=6;pInv=0;mounted=false;dragon.on=false;});
for(var i=0;i<15;i++)IceMoth.effects(.05);`);
assert.equal(run(`LDRCampaign.actor('guest').vars.pHp`),4,'Original target is hit after focus switches');
assert.equal(run(`LDRCampaign.actor('host').vars.pHp`),6,'Closer partner does not receive remote damage');
console.log('PASS: late-game Ice Moth projectile ownership survives focus changes.');
await run('SpiderQueenWeb.ensureArt()');
run(`SpiderQueenDemo.inspect=()=>({ready:true});SpiderQueenBoss.restore(true);dragonOff=false;devDragonPassive=false;dragonReady=true;foesHeld=false;
editorDraftReady=false;loadMap('pyramid_queen');scene=null;bossScene=null;fadeDir=0;ovl=null;arenaLock=expandedTempleArenas()[0];arenaT=1;
LDRCampaign.withActor('guest',()=>{P.x=103;P.y=200;P.act=null;pHp=6;pInv=0;Object.assign(dragon,{on:true,down:false,x:130,y:200,placed:MAPID,air:false,knockdown:0,hp:40,maxHp:40});});
LDRCampaign.withActor('host',()=>{P.x=240;P.y=245;P.act=null;pHp=6;Object.assign(dragon,{on:true,down:false,x:240,y:245,placed:MAPID,air:false,hp:40,maxHp:40});});
Object.assign(foes[0],{x:103,y:135,st:'idle',t:0,webCool:0});
for(var i=0;i<44;i++)stepCombat(.05);`);
assert.equal(run('SpiderQueenBoss.coopOwner()'),'guest');
assert.equal(run(`LDRCampaign.withActor('guest',()=>SpiderQueenBoss.webbed())`),true);
assert.equal(run(`LDRCampaign.withActor('host',()=>SpiderQueenBoss.holdPlayer(.05))`),false,'The partner is not teleported into another rider’s web');
assert.equal(run(`LDRCampaign.withActor('guest',()=>SpiderQueenBoss.commandBreath('fire'))`),true);
assert.equal(run('SpiderQueenBoss.inspect().web.phase'),'burning');
console.log('PASS: Spider Queen capture belongs to one rider and their dragon; the partner stays free and Fire still releases the web.');
