import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
import {gameDom} from './helpers-game-dom.mjs';
const dom=gameDom(),{run,context:c}=await loadEditorGame(process.cwd(),console,{document:dom.document,furniture:false});
const box=dom.element('bagAsk'),rows=dom.element('askRows');box.append(rows);
const click=node=>{assert(node);node.onclick({stopPropagation(){}});};
run(`quest=Q.DONE;dragon.on=true;dragonOff=false;thornwellRoyal.stage=7;faceToward=()=>{};
openNpcTopics({n:'Linna',x:150,y:150,d:['Hello']});`);
assert.equal(box.querySelector('.deckHeader').parentNode,box,'Banner spans the panel independently of the topic columns');
assert.equal(box.querySelector('.deckProfileHint').textContent,'View profile ▾','Profile access has a clear action label');
const original=run('askPick');
click(box.querySelector('.deckProfileToggle'));
assert.equal(run('ask._profileOpen'),true);
assert.match(box.querySelector('.deckProfile').querySelector('p').textContent||run(`EmberConversationView.profile('Linna').bio`),/mill/i);
assert.equal(run(`EmberConversationView.profile('King Halvard').role`),'King of Emberfell','Profiles never reuse obsolete sprite/editor roles');
assert.equal(run(`EmberConversationView.profile('Bess').home`),'Thornwell');
run('askStep(1)');assert.equal(run('askPick'),original,'Hidden choices cannot be selected through profile navigation');
run('askTake()');assert.equal(run('ask._profileOpen'),false,'A returns from the profile without choosing an invisible topic');
click(rows.querySelectorAll('.deckTab').find(n=>n.textContent==='The realm'));
click(box.querySelector('.deckProfileToggle'));run('askBack()');
assert.equal(run('ask._deckFilter'),'world','Profile Back preserves the previous filtered topic list');
run('askBack()');assert.equal(run('ask._deckFilter'),'all','Category Back restores all topics');
run(`askShut();MAPID='world';dragonIntroDone=true;dragon.air=false;openDragonConversation('history');`);
click(box.querySelector('.deckBack'));assert.equal(run('ask.topicScope'),'root','Folder Back returns to Aurelius’s previous topic list');
assert(!rows.querySelectorAll('.deckTopic').some(n=>/chapter/i.test(n.getAttribute('aria-label'))));
run(`askShut();thornwellRoyal.stage=3;var king={n:'King Halvard',thornwellRoyal:true,x:150,y:150};
var dismissals=0;thornwellDismissAudience=()=>{dismissals++;};
openThornwellAudience(king);ask._deckFilter='world';askDraw();`);
run('askBack()');assert.equal(run('dismissals'),0,'Leaving a filter does not dismiss the king');
click(box.querySelector('.deckProfileToggle'));run('askBack()');assert.equal(run('dismissals'),0);
click(box.querySelector('.deckClose'));assert.equal(run('dismissals'),1,'Leaving the audience still runs its required story callback');

// Conversations leave the gameplay camera alone, including authored scenes,
// gift overlays, menu navigation and alternating dialogue portraits.
run(`askShut();scene=null;sayNpc=null;sayOff();MAPID='world';VW=800;VH=420;
P.x=100;P.y=130;mode='play';camFree=false;greenCamera=null;hatchCamera=null;
bossScene=null;deflectCamera=null;revealing=false;devUnlocked=false;EmberRiding.skip();
cam={x:-60,y:-10,z:2.2};cameraPresentation=null;cameraLogical=null;
var beforeCamera={...cam};presentCamera(.016);
openNpcTopics({n:'Linna',x:140,y:130,d:['Hello']});presentCamera(.016);`);
const before=run('beforeCamera');
assert.deepEqual(run('({...cam})'),before,'Opening a conversation never zooms or pans');
assert.equal(dom.element('face').dataset.speaker,'Linna','The greeting uses the existing dialogue portrait');
assert.equal(dom.element('face').className,'left');
assert.equal(run('typeFull'),run('NPC_TOPIC_GREETINGS.Linna'));
assert.equal(dom.element('say').dataset.advanceHint,'Choose a topic below');
run('ask._profileOpen=true;askDraw();presentCamera(.016);');
assert.deepEqual(run('({...cam})'),before,'Opening a profile never changes the camera');
run(`askShut();portraitPackImages.set(portraitFor('Corin').pack,{src:'corin-test-portrait'});
scene={lines:['Linna: A memory from the mill.','Corin: Tell me more.'],i:0,t:1,npcActor:{n:'Linna',x:140,y:130}};
showScene();presentCamera(.016);`);
assert.equal(dom.element('face').dataset.speaker,'Linna');
assert.equal(dom.element('face').className,'left');
assert(dom.element('sayname').classList.contains('right'));
run('scene.i=1;showScene();presentCamera(.016);');
assert.equal(dom.element('face').dataset.speaker,'Corin');
assert.equal(dom.element('face').className,'right');
assert(dom.element('sayname').classList.contains('left'));
assert.deepEqual(run('({...cam})'),before,'Switching speakers preserves the normal camera');
run(`scene={telepathy:true,lines:['Aurelius: Corin.'],i:0,t:1};showScene();presentCamera(.016);`);
assert.deepEqual(run('({...cam})'),before,'Aurelius’s introduction does not zoom');
run(`scene={nanGifts:true,npcActor:{n:'Nan Ferrow',x:100,y:166},lines:['Nan Ferrow: Take this.'],i:0,t:1};
showScene();presentCamera(.016);revealing=true;sayOff();presentCamera(.016);`);
assert.deepEqual(run('({...cam})'),before,'Nan’s gifts do not change the camera');
run('revealing=false;scene.silent=true;scene.npcActor.y+=80;presentCamera(.016);');
assert.deepEqual(run('({...cam})'),before,'Nan’s walk-off does not move the camera');
run('scene=null;sayOff();openNpcTopics({n:"Linna",x:140,y:130,d:["Hello"]});');
assert.equal(dom.element('face').style.display,'block','A topic list keeps its greeting portrait above the dialogue');
assert.equal(c.document.querySelectorAll('.conversationPortrait').length,0,'No paired portrait overlay is created');
run('askShut();presentCamera(.016)');
assert(!dom.element('say').classList.contains('on'),'Goodbye dismisses the greeting');
assert.deepEqual(run('({...cam})'),before,'Goodbye does not zoom out');
assert.equal(run(`playerFacingText('Millwood, indoors (house26)')`),'Millwood, indoors');
assert.equal(run(`playerFacingText('Visit house26')`),'Visit '+run('W.maps.house26.title'));
run(`openNpcTopics({n:'Linna',x:140,y:130,d:['Hello']});ask.opts.push({n:'Visit house26',go:()=>{}});askDraw();`);
assert(!rows.querySelectorAll('.deckTopic').some(n=>/house\d/i.test(n.getAttribute('aria-label'))));
console.log('PASS: profiles, safe Back/leave paths, unique greetings, single alternating portrait, and normal camera throughout conversations and gifts.');
