import assert from 'node:assert/strict';
import fs from 'node:fs';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
import {gameDom} from './helpers-game-dom.mjs';
const dom=gameDom(),{run,context:c}=await loadEditorGame(process.cwd(),console,{document:dom.document,furniture:false});
const box=dom.element('bagAsk'),rows=dom.element('askRows'),say=dom.element('say'),canvas=dom.element('cv');box.append(rows);
run(`MAPID='world';MD=W.maps.world;MW=MD.w;MH=MD.h;terr=new Uint8Array(MW*MH);mode='play';gameplayStarted=true;quest=Q.DONE;dragon.on=true;dragonOff=false;dragonIntroDone=true;
thornwellRoyal.stage=7;faceToward=()=>{};dragonConversationReaction=()=>{};saveGame=()=>{};
var person={n:'Hettie',x:100,y:100,d:['Hettie: A pleasant morning.']};
P.x=100;P.y=130;EmberConversationFlow.prompt(person);`);
const select=name=>{if(run('EmberConversationFlow.welcoming()'))box.querySelector('.conversationChat').onclick({stopPropagation(){}});c.selection=name;run('askPick=ask.opts.findIndex(o=>o.n===selection);askTake();');};
assert(run('ask.conversationPrompt'),'First interaction opens a small invitation');
assert(!run('EmberConversationFlow.active()'),'No full-screen session before confirming Talk');
assert(!box.classList.contains('conversationTopics'));
run('askBack()');assert.equal(run('ask'),null,'B cancels the invitation');
run('EmberConversationFlow.prompt(person)');select('Talk');
assert(run('EmberConversationFlow.active()'));
assert.equal(box.getAttribute('aria-modal'),'true');
assert.equal(say.parentNode,box.querySelector('.conversationNpcSpeech'),'NPC dialogue stays in the upper lane');
const step=()=>run('if(scene)scene.t=1;EmberConversationFlow.advance();');
const finish=()=>{for(let i=0;i<25&&run('!!scene||!!sayNpc');i++){assert(!run('ask?.replyChoices'),'Test must choose a reply explicitly');run('typeAll()');step();}};
const tap=(target=canvas)=>{dom.dispatch(target,'pointerdown');dom.dispatch(target,'pointerup');dom.dispatch(target,'click');};
const next=()=>box.querySelector('.conversationNext').onclick({stopPropagation(){}});
const greetings=Object.fromEntries(fs.readFileSync('assets/dialogue/npc-greetings.tsv','utf8').trim().split('\n').map(row=>row.split('|')));
assert.equal(Object.keys(greetings).length,144);
assert.equal(new Set(Object.values(greetings)).size,144,'Every character has a unique greeting');
assert.deepEqual(JSON.parse(run('JSON.stringify(NPC_TOPIC_GREETINGS)')),greetings);
const responses=Object.fromEntries(fs.readFileSync('assets/dialogue/corin-greetings.tsv','utf8').trim().split('\n').map(row=>row.split('|')));
assert.deepEqual(JSON.parse(run('JSON.stringify(CORIN_TOPIC_GREETINGS)')),responses);
assert.deepEqual(Object.keys(responses),Object.keys(greetings));
assert.equal(new Set(Object.values(responses)).size,144);
const player=box.querySelector('.conversationPlayer'),chat=box.querySelector('.conversationChat');
assert.equal(player.dataset.mode,'welcome');assert.equal(chat.textContent,'Chat with Hettie');assert(!chat.hidden);
assert.equal(player.querySelector('.conversationCorinEcho').textContent,responses.Hettie);
assert(player.querySelector('.conversationWorkspace').hidden);assert(!player.querySelector('.conversationSpeaker').hidden);
const greetingPick=run('askPick');run('askStep(1)');assert.equal(run('askPick'),greetingPick,'Hidden topics cannot be navigated');
next();assert.equal(player.dataset.mode,'topics','Next opens Chat without choosing an invisible topic');
assert.equal(run('scene'),null);assert(player.querySelector('.conversationSpeaker').hidden);
assert(!player.querySelector('.conversationWorkspace').hidden);assert(chat.hidden);
run('EmberConversationFlow.secondary()');assert.equal(player.dataset.mode,'welcome');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
chat.onclick({stopPropagation(){}});assert.equal(player.dataset.mode,'topics');
assert.equal(run('typeFull'),greetings.Hettie);
assert.equal(run('typeWho'),'Hettie');assert(say.classList.contains('on'));
tap(say);tap();assert.equal(run('typeFull'),greetings.Hettie,'Greeting stays until a topic is chosen');
assert.equal(run('scene'),null,'A greeting never starts a quest scene');
run('ask._profileOpen=true;askDraw();askBack();');assert.equal(run('typeFull'),greetings.Hettie);
select('Your first herd');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'listen');
assert.equal(run('ask'),null,'Speech continues with no modal ask blocking its clock');
assert.equal(box.style.display,'grid');
assert(run('document.body.classList.contains("topics-open")'));
assert(run('document.body.classList.contains("conversation-speaking")'));
assert(box.querySelectorAll('.deckTopic').every(b=>b.disabled));
assert(box.querySelector('.conversationNext'));
say.scrollHeight=800;say.clientHeight=120;say.scrollTop=50;
dom.dispatch(say,'touchstart',{touches:[{clientX:10,clientY:150}]});
assert.equal(run('lockEl'),say,'The actual dialogue is also a native scroller');
assert(!dom.dispatch(say,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:90}]}).defaultPrevented);
dom.dispatch(say,'touchend');
assert(!box.querySelector('.conversationContinue'));
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'speech');
assert(run('!typeDone()'));
tap(say);assert(run('!typeDone()'),'Full conversations advance only with A, leaving speech free to scroll');
next();assert(run('typeDone()'));assert.equal(run('scene.i'),0,'First A only completes the text');
run('scene.t=1');next();assert(run('ask.replyChoices'),'Second tap offers Corin replies');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'reply');
assert.equal(box.style.display,'grid');assert.equal(run('typeWho'),'Hettie','NPC’s line remains while choosing');
assert(!rows.querySelector('.deckTabs'));assert(rows.querySelector('.deckReplyPrompt'));
assert.equal(rows.querySelectorAll('.deckTopic').length,0,'Replies use a distinct menu, not topic cards');
assert.equal(rows.querySelectorAll('.deckReply').length,3);assert(rows.classList.contains('replyMenu'));
assert(player.querySelector('.conversationSpeaker').hidden);
assert.equal(run('ask.opts.filter(o=>!o.head).length'),3,'Original, authored alternative and other story paths');
assert(box.querySelector('.conversationGoodbye'),'B remains available while choosing an optional reply');
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'replies');
const waiting=run('scene.i');tap();assert.equal(run('scene.i'),waiting,'Tapping scenery never chooses a reply');
select('I would have offered it an apple.');assert.equal(run('typeWho'),'Corin');
assert.match(run('typeFull'),/apple/);
assert.equal(say.parentNode,box.querySelector('.conversationCorinSpeech'),'Corin speaks in the lower lane');
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'speech');
assert(box.querySelector('.conversationNpcEcho').textContent.length>0,'The NPC’s last words stay above Corin’s response');
assert.equal(box.querySelector('.conversationStage').querySelector('.conversationPortrait').dataset.speaker,'Hettie');
assert(!box.querySelector('.deckReadRing'),'Reply cards do not display a meaningless zero-topic counter');
assert.equal(rows.querySelectorAll('.deckReply').find(n=>n.dataset.selected==='true').dataset.askIndex,2,'The selected reply remains highlighted while it is spoken');assert.equal(box.style.display,'grid');
run('typeAll()');step();assert.equal(run('typeWho'),'Hettie');assert.match(run('typeFull'),/spoiled/);
finish();assert.equal(run('ask.npcConversation'),'Hettie');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'welcome');
assert(!player.querySelector('.conversationSpeaker').hidden);assert(!box.querySelector('.conversationChat').hidden);
assert(!box.querySelector('.deckHistoryToggle'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
box.querySelector('.conversationChat').onclick({stopPropagation(){}});
// Touch locking must recognize the actual nested scroller, not the full-screen shell.
const workspace=box.querySelector('.conversationWorkspace');
workspace.scrollHeight=1200;workspace.clientHeight=280;workspace.scrollTop=80;
box.scrollHeight=600;box.clientHeight=600;
const card=rows.querySelector('.deckTopic');
dom.dispatch(card,'touchstart',{touches:[{clientX:10,clientY:180}]});
assert.equal(run('lockEl'),workspace,'A drag beginning on a topic locks the inner list');
const drag=dom.dispatch(card,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:100}]});
assert(!drag.defaultPrevented,'The game permits the browser to scroll the topic list');
dom.dispatch(card,'touchend');
box.querySelector('.deckProfileToggle').onclick();
const dossier=box.querySelector('.conversationDossier');
assert(!dossier.hidden);assert.equal(dossier.parentNode,box,'Profile has its own full conversation-sized page');
dossier.scrollHeight=1000;dossier.clientHeight=400;dossier.scrollTop=80;
dom.dispatch(dossier,'touchstart',{touches:[{clientX:10,clientY:180}]});
assert.equal(run('lockEl'),dossier);
assert(!dom.dispatch(dossier,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:100}]}).defaultPrevented);
dom.dispatch(dossier,'touchend');run('askBack()');
// The secondary control returns from replies, then becomes Goodbye at the root.
select('Your first herd');next();run('scene.t=1');next();assert(run('ask.replyChoices'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
run("EmberConversationFlow.key({key:'b',preventDefault(){}})");
assert(run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
run("EmberConversationFlow.key({key:'b',preventDefault(){}})");
assert(!run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
run('openNpcTopics(person)');select('Your first herd');
box.querySelector('.conversationGoodbye').onclick({stopPropagation(){}});
assert(!run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
run('openNpcTopics(person)');
// Follow a different personal thread without dismissing/reopening the panel.
select('Your first herd');run('typeAll();scene.t=1');step();
select('Tell me about “A day off”.');assert.equal(run('typeWho'),'Corin');
run('typeAll()');step();assert.equal(run('typeWho'),'Hettie');assert.match(run('typeFull'),/one morning/);
run('typeAll();scene.t=1');step();assert(run('ask.replyChoices'));run('askBack()');
assert.equal(run('ask.npcConversation'),'Hettie');assert.equal(run('scene'),null);
// The actual pointer path rejects drags, multi-touch and synthetic click echoes.
select('Your first herd');
dom.dispatch(canvas,'pointerdown');dom.dispatch(canvas,'pointermove',{clientX:30});dom.dispatch(canvas,'pointerup',{clientX:30});dom.dispatch(canvas,'click');
assert(run('!typeDone()'),'Drag never completes dialogue');
dom.dispatch(canvas,'pointerdown');dom.dispatch(canvas,'pointerdown',{pointerId:2,isPrimary:false});dom.dispatch(canvas,'pointerup',{pointerId:2,isPrimary:false});dom.dispatch(canvas,'pointerup');
assert(run('!typeDone()'),'Pinch never completes dialogue');
const ui=dom.element('testButton');ui.tagName='BUTTON';dom.element('stage').append(ui);
tap(ui);assert(run('!typeDone()'),'Unrelated controls do not advance speech through a stage ancestor');
next();assert(run('typeDone()'));assert.equal(run('scene.i'),0);
run('scene.t=1');next();run('askBack()');
// Greeting completion returns to the same NPC; gifts are not bypassed.
select('Hello!');assert(run('sayNpc===person'));
assert(box.querySelector('.conversationGoodbye').disabled,'Required NPC exchanges finish before Goodbye');
next();assert(run('typeDone()'));next();
assert.equal(run('ask.npcConversation'),'Hettie');
run(`askShut();var gifted={n:'Sela',x:100,y:100,d:['Sela: Take care.']};glassShield=true;openNpcTopics(gifted);glassShield=false;`);
select('Hello!');assert.equal(run('ask'),null);finish();
assert(run('glassShield'));assert(run('revealing'));
assert.equal(dom.element('reveal').parentNode,box,'Gift reveal shares the conversation grid, leaving A accessible');
assert(!box.querySelector('.conversationNext').disabled);
assert(box.querySelector('.conversationGoodbye').disabled);assert(!run('EmberConversationFlow.goodbye()'),'Goodbye cannot interrupt a reward');assert.equal(run('ask'),null,'Gift reveal finishes before topics return');
next();assert.equal(run('ask.npcConversation'),'Sela');
// A temporarily full-screen shop returns to the ongoing conversation.
run("drawMerchantShop=()=>{document.getElementById('bagAsk').style.display='none';};askShut();person.sells=true;openNpcTopics(person)");select('Browse your supplies');
assert(run('!!ask.shop'));run('askBack();EmberConversationFlow.tick()');assert.equal(run('ask.npcConversation'),'Hettie','B closes shopping and resumes the conversation');
select('Goodbye');assert.equal(run('ask'),null);assert(!run('EmberConversationFlow.active()'));assert.equal(box.style.display,'none');
assert(!say.classList.contains('on'),'Goodbye removes the default dialogue too');
assert.equal(say.parentNode,c.document.body,'Closing full conversation restores the cutscene dialogue overlay');
assert.equal(dom.element('reveal').parentNode,c.document.body,'Gift overlay returns to its normal home too');
run('EmberConversationFlow.prompt(person)');assert(run("ask.opts.some(o=>o.n==='Buy supplies')"),'Merchants offer Talk and Buy before opening either full screen');
select('Buy supplies');assert(run('!!ask.shop'));assert(!run('EmberConversationFlow.active()'));
run('askShut()');
// Ordinary story dialogue gains tapping without creating a conversation panel.
run(`playScene(['Corin: Wait for me.','Hettie: No running.'],{npcActor:person});`);
assert(!run('EmberConversationFlow.active()'),'A story scene does not create a full conversation');
assert.equal(say.parentNode,c.document.body);
tap();assert(run('typeDone()'));assert.equal(run('scene.i'),0);run('scene.t=1');tap();assert.equal(run('scene.i'),1);
run('scene.hold=()=>false;showScene()');tap();assert.equal(run('scene.i'),1,'Cinematic holds cannot be tapped past');
run('scene=null;sayOff()');
// Every cast member has an original and a distinct authored answer, including
// the eleven villagers whose personal stories live in the expansion file.
const source=Object.fromEntries(fs.readFileSync('assets/dialogue/npc-replies.tsv','utf8').trim().split('\n').map(l=>{const [n,...reply]=l.split('|');return[n,reply];}));
assert.equal(Object.keys(source).length,143);
assert.deepEqual(JSON.parse(run('JSON.stringify(NPC_REPLY_BRANCHES)')),source);
for(const [name,reply]of Object.entries(source)){
 c.speaker=name;c.reply=reply;
 run(`askShut();scene=null;sayNpc=null;var actor={n:speaker,x:100,y:100,d:['Hello']};var authored=npcStoryTopics(actor).find(t=>t.reply);
 if(!authored)throw Error('Missing branch '+speaker);
 ask={quick:1,npcConversation:speaker,npcActor:actor,opts:[{n:'Goodbye'}]};askDraw();
 if(typeWho!==speaker||typeFull!==NPC_TOPIC_GREETINGS[speaker])throw Error('Missing greeting '+speaker);
 if(document.getElementById('bagAsk').querySelector('.conversationCorinEcho').textContent!==CORIN_TOPIC_GREETINGS[speaker])throw Error('Missing Corin greeting '+speaker);
 EmberConversationFlow.openChat();EmberConversationFlow.take({n:authored.title,go:()=>EmberConversationFlow.playTopic(actor,authored)});typeAll();scene.t=1;EmberConversationFlow.advance();`);
 assert(run('ask?.replyChoices'),name+' gets reply choices');
 assert(run('ask.opts.some(o=>o.n===reply[0])'),name+' has their specific branch');
 select(reply[0]);run('typeAll();scene.t=1');step();
 assert.equal(run('typeFull'),reply[1],name+' responds to the selected words');
}
// Aurelius participates too, with distinct responses to personal questions.
run(`askShut();scene=null;sayNpc=null;MAPID='world';dragon.air=false;P.act=null;EmberConversationFlow.prompt(dragon,{dragon:true});`);
assert(!run('EmberConversationFlow.active()'));select('Talk');select('Dragons and our bond');
assert.equal(run('typeFull'),greetings.Aurelius);
assert.equal(dom.element('say').dataset.telepathy,'true','Aurelius greets Corin through the bond');
select('Why did you choose me?');
for(let i=0;i<10&&!run('ask?.replyChoices');i++){run('typeAll();if(scene)scene.t=1');step();}
assert(run('ask?.replyChoices'));assert(run('ask.opts.some(o=>/disappoint/.test(o.n))'));
assert(box.classList.contains('dragonTalk'),'Aurelius’s theme persists through branching replies');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
select('What if I disappoint you?');run('typeAll();scene.t=1');step();assert.equal(run('typeWho'),'Aurelius');assert.match(run('typeFull'),/mistakes/);
finish();assert.equal(run('ask.topicScope'),'dragons');
// Changing area / loading another scene cannot resurrect an old conversation.
run(`MAPID='house0';EmberConversationFlow.tick()`);assert(!run('EmberConversationFlow.active()'));assert.equal(run('ask'),null);
console.log('PASS: persistent parchment, actual tap/drag/pinch routing, authored choices for 143 NPCs and Aurelius, branching responses, root/branch Back, greetings, gifts, shopping and area teardown.');
