import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
import {gameDom} from './helpers-game-dom.mjs';
const dom=gameDom(),{run,context:c}=await loadEditorGame(process.cwd(),console,{document:dom.document,furniture:false});
const box=dom.element('bagAsk'),rows=dom.element('askRows');box.append(rows);
const click=node=>{assert(node);node.onclick({stopPropagation(){}});};
run(`quest=Q.DONE;dragon.on=true;dragonOff=false;thornwellRoyal.stage=7;faceToward=()=>{};
openNpcTopics({n:'Linna',x:150,y:150,d:['Hello']});`);
assert(!box.querySelector('.deckHeader'),'No redundant top banner');
assert.equal(box.querySelector('.deckProfileToggle').parentNode,box.querySelector('.conversationFooter'));
assert.equal(box.querySelector('.conversationStage').querySelector('.conversationSpeaker').parentNode,box.querySelector('.conversationNpcSpeech'),'NPC portrait attaches directly to its speech box');
assert.equal(box.querySelector('.conversationPlayer').querySelector('.conversationSpeaker').parentNode,box.querySelector('.conversationCorinSpeech'),'Corin portrait attaches directly to his speech box');
assert.equal(box.querySelector('.deckProfileToggle').textContent,'View Character Profile');
assert(!box.querySelector('.deckHistoryToggle'));assert(!box.querySelector('.deckBack'));
assert.equal(box.querySelector('.conversationNext').textContent,'Next');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
const original=run('askPick');
click(box.querySelector('.deckProfileToggle'));
assert.equal(run('ask._profileOpen'),true);
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
assert(box.querySelector('.deckProfileQuote').querySelector('blockquote'),'The profile quote has its own banner');
assert.match(box.querySelector('.deckProfile').querySelector('p').textContent||run(`EmberConversationView.profile('Linna').bio`),/mill/i);
assert.equal(run(`EmberConversationView.profile('King Halvard').role`),'King of Emberfell','Profiles never reuse obsolete sprite/editor roles');
assert.equal(run(`EmberConversationView.profile('Bess').home`),'Thornwell');
run('askStep(1)');assert.equal(run('askPick'),original,'Hidden choices cannot be selected through profile navigation');
click(box.querySelector('.conversationGoodbye'));assert.equal(run('ask._profileOpen'),false,'The secondary button returns from the profile');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
click(box.querySelector('.conversationChat'));
assert(!rows.querySelector('.deckTabs'),'Topic categories are gone');
run("ask._deckFilter='world';askDraw()");
assert.equal(run('ask._deckFilter'),'all','Old saved filters cannot hide topics');
click(box.querySelector('.deckProfileToggle'));click(box.querySelector('.conversationGoodbye'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
click(box.querySelector('.conversationGoodbye'));assert(run('EmberConversationFlow.welcoming()'));
run(`askShut();MAPID='world';dragonIntroDone=true;dragon.air=false;openDragonConversation('history');`);
assert(box.classList.contains('dragonTalk'));click(box.querySelector('.conversationChat'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
assert(!rows.querySelectorAll('.deckTopic').some(n=>/Back to our other questions/.test(n.getAttribute('aria-label'))),'No duplicate Back card');
click(box.querySelector('.conversationGoodbye'));assert.equal(run('ask.topicScope'),'root','Folder Back returns to Aurelius’s previous topic list');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
click(box.querySelector('.conversationGoodbye'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
click(box.querySelector('.deckProfileToggle'));assert(box.classList.contains('dragonTalk'),'Aurelius keeps the bond theme in his profile');
assert(box.querySelector('.deckProfileQuote').querySelector('blockquote'));
click(box.querySelector('.conversationGoodbye'));
assert(!rows.querySelectorAll('.deckTopic').some(n=>/chapter/i.test(n.getAttribute('aria-label'))));
run(`askShut();thornwellRoyal.stage=3;var king={n:'King Halvard',thornwellRoyal:true,x:150,y:150};
var dismissals=0;thornwellDismissAudience=()=>{dismissals++;};
openThornwellAudience(king);EmberConversationFlow.openChat();`);
assert.equal(run('dismissals'),0,'Opening topics does not dismiss the king');
click(box.querySelector('.deckProfileToggle'));click(box.querySelector('.conversationGoodbye'));assert.equal(run('dismissals'),0);
click(box.querySelector('.conversationGoodbye'));assert.equal(run('dismissals'),0,'Back restores the king’s greeting');
click(box.querySelector('.conversationGoodbye'));assert.equal(run('dismissals'),1,'Leaving the audience still runs its required story callback');

// Conversations leave the gameplay camera alone, including authored scenes,
// gift overlays, menu navigation and alternating dialogue portraits.
run(`askShut();scene=null;sayNpc=null;sayOff();MAPID='world';VW=800;VH=420;
P.x=100;P.y=130;mode='play';camFree=false;greenCamera=null;hatchCamera=null;
bossScene=null;deflectCamera=null;revealing=false;devUnlocked=false;EmberRiding.skip();
cam={x:-60,y:-10,z:2.2};cameraPresentation=null;cameraLogical=null;
var beforeCamera={...cam};presentCamera(.016);
openNpcTopics({n:'Linna',x:140,y:130,d:['Hello']});presentCamera(.016);`);
assert(!box.classList.contains('dragonTalk'),'Human conversations never inherit the dragon theme');
const before=run('beforeCamera');
assert.deepEqual(run('({...cam})'),before,'Opening a conversation never zooms or pans');
assert.equal(dom.element('face').dataset.speaker,'Linna','The greeting uses the existing dialogue portrait');
assert.equal(dom.element('face').className,'left');
assert.equal(run('typeFull'),run('NPC_TOPIC_GREETINGS.Linna'));
assert.equal(dom.element('say').dataset.advanceHint,'Choose Chat to begin');
run('ask._profileOpen=true;askDraw();presentCamera(.016);');
assert.deepEqual(run('({...cam})'),before,'Opening a profile never changes the camera');
run(`askShut();portraitPackImages.set(portraitFor('Corin').pack,{src:'corin-test-portrait'});
scene={lines:['Linna: A memory from the mill.','Corin: Tell me more.'],i:0,t:1,npcActor:{n:'Linna',x:140,y:130}};
showScene();presentCamera(.016);`);
assert.equal(dom.element('face').dataset.speaker,'Linna');
assert.equal(dom.element('face').className,'left');
assert(dom.element('sayname').classList.contains('right'));
run('scene.i=1;showScene();presentCamera(.016);');
assert.equal(dom.element('face').dataset.speaker,'Corin');
assert.equal(dom.element('face').className,'right');
assert(dom.element('sayname').classList.contains('left'));
assert.deepEqual(run('({...cam})'),before,'Switching speakers preserves the normal camera');
run(`scene={telepathy:true,lines:['Aurelius: Corin.'],i:0,t:1};showScene();presentCamera(.016);`);
assert.deepEqual(run('({...cam})'),before,'Aurelius’s introduction does not zoom');
run(`scene={nanGifts:true,npcActor:{n:'Nan Ferrow',x:100,y:166},lines:['Nan Ferrow: Take this.'],i:0,t:1};
showScene();presentCamera(.016);revealing=true;sayOff();presentCamera(.016);`);
assert.deepEqual(run('({...cam})'),before,'Nan’s gifts do not change the camera');
run('revealing=false;scene.silent=true;scene.npcActor.y+=80;presentCamera(.016);');
assert.deepEqual(run('({...cam})'),before,'Nan’s walk-off does not move the camera');
run('scene=null;sayOff();openNpcTopics({n:"Linna",x:140,y:130,d:["Hello"]});');
assert.equal(dom.element('face').style.display,'block','A topic list keeps its greeting portrait above the dialogue');
assert.equal(c.document.querySelectorAll('.conversationPortrait').length,2,'Full conversation has a fixed portrait for each participant');
run('askShut();presentCamera(.016)');
assert(!dom.element('say').classList.contains('on'),'Goodbye dismisses the greeting');
assert.deepEqual(run('({...cam})'),before,'Goodbye does not zoom out');
assert.equal(run(`playerFacingText('Millwood, indoors (house26)')`),'Millwood, indoors');
assert.equal(run(`playerFacingText('Visit house26')`),'Visit '+run('W.maps.house26.title'));
run(`openNpcTopics({n:'Linna',x:140,y:130,d:['Hello']});ask.opts.push({n:'Visit house26',go:()=>{}});askDraw();`);
assert(!rows.querySelectorAll('.deckTopic').some(n=>/house\d/i.test(n.getAttribute('aria-label'))));
console.log('PASS: profiles, safe Back/leave paths, distinct profiles, fixed conversation portraits, alternating cutscene portraits, and normal camera throughout conversations and gifts.');
