import assert from 'node:assert/strict';
import fs from 'node:fs';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
import {gameDom} from './helpers-game-dom.mjs';
const dom=gameDom(),{run,context:c}=await loadEditorGame(process.cwd(),console,{document:dom.document,furniture:false});
const box=dom.element('bagAsk'),rows=dom.element('askRows'),say=dom.element('say'),canvas=dom.element('cv');box.append(rows);
run(`MAPID='world';MD=W.maps.world;MW=MD.w;MH=MD.h;terr=new Uint8Array(MW*MH);mode='play';gameplayStarted=true;quest=Q.DONE;dragon.on=true;dragonOff=false;dragonIntroDone=true;
thornwellRoyal.stage=7;faceToward=()=>{};dragonConversationReaction=()=>{};saveGame=()=>{};
var person={n:'Hettie',x:100,y:100,d:['Hettie: A pleasant morning.']};
P.x=100;P.y=130;EmberConversationFlow.prompt(person);`);
const select=name=>{if(run('EmberConversationFlow.welcoming()'))box.querySelector('.conversationChat').onclick({stopPropagation(){}});c.selection=name;run('askPick=ask.opts.findIndex(o=>o.n===selection);askTake();');};
assert(run('ask.conversationPrompt'),'First interaction opens a small invitation');
assert(!run('EmberConversationFlow.active()'),'No full-screen session before confirming Talk');
assert(!box.classList.contains('conversationTopics'));
run('askBack()');assert.equal(run('ask'),null,'B cancels the invitation');
run('EmberConversationFlow.prompt(person)');select('Talk');
assert(run('EmberConversationFlow.active()'));
assert.equal(run('EmberConversationFlow.partner()'),'Hettie','Session keeps the station actor while dialogue changes');
assert.equal(box.getAttribute('aria-modal'),'true');
assert.equal(say.parentNode,box.querySelector('.conversationNpcSpeech'),'NPC dialogue stays in the upper lane');
const step=()=>run('if(scene)scene.t=1;EmberConversationFlow.advance();');
const finish=()=>{for(let i=0;i<25&&run('!!scene||!!sayNpc');i++){assert(!run('ask?.replyChoices'),'Test must choose a reply explicitly');run('typeAll()');step();}};
const tap=(target=canvas)=>{dom.dispatch(target,'pointerdown');dom.dispatch(target,'pointerup');dom.dispatch(target,'click');};
const next=()=>box.querySelector('.conversationNext').onclick({stopPropagation(){}});
const greetings=Object.fromEntries(fs.readFileSync('assets/dialogue/npc-greetings.tsv','utf8').trim().split('\n').map(row=>row.split('|')));
assert.equal(Object.keys(greetings).length,143);
assert(!('Greta' in greetings),'Removed Greta is absent from the greeting cast');
assert.equal(new Set(Object.values(greetings)).size,143,'Every character has a unique greeting');
assert.deepEqual(JSON.parse(run('JSON.stringify(NPC_TOPIC_GREETINGS)')),greetings);
const responses=Object.fromEntries(fs.readFileSync('assets/dialogue/corin-greetings.tsv','utf8').trim().split('\n').map(row=>row.split('|')));
assert.deepEqual(JSON.parse(run('JSON.stringify(CORIN_TOPIC_GREETINGS)')),responses);
assert.deepEqual(Object.keys(responses),Object.keys(greetings));
assert.equal(new Set(Object.values(responses)).size,143);
const player=box.querySelector('.conversationPlayer'),chat=box.querySelector('.conversationChat');
assert.equal(player.dataset.mode,'welcome');assert(!box.querySelector('.conversationContext'));assert(!rows.querySelector('.deckTabs'));
assert.equal(chat.textContent,'Chat');assert(!chat.disabled);assert.equal(chat.parentNode,box.querySelector('.conversationFooter'));
assert.equal(player.querySelector('.conversationCorinEcho').textContent,responses.Hettie);
assert(player.querySelector('.conversationWorkspace').hidden);assert(!player.querySelector('.conversationSpeaker').hidden);
const greetingPick=run('askPick');run('askStep(1)');assert.equal(run('askPick'),greetingPick,'Hidden topics cannot be navigated');
next();assert.equal(player.dataset.mode,'topics','Next opens Chat without choosing an invisible topic');
assert.equal(run('scene'),null);assert(player.querySelector('.conversationSpeaker').hidden);
assert(!player.querySelector('.conversationWorkspace').hidden);assert(chat.disabled);assert.equal(chat.getAttribute('aria-expanded'),'true');
run('EmberConversationFlow.secondary()');assert.equal(player.dataset.mode,'welcome');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
chat.onclick({stopPropagation(){}});assert.equal(player.dataset.mode,'topics');
assert.equal(run('typeFull'),greetings.Hettie);
assert.equal(run('typeWho'),'Hettie');assert(say.classList.contains('on'));
tap(say);tap();assert.equal(run('typeFull'),greetings.Hettie,'Greeting stays until a topic is chosen');
assert.equal(run('scene'),null,'A greeting never starts a quest scene');
run('ask._profileOpen=true;askDraw();askBack();');assert.equal(run('typeFull'),greetings.Hettie);
select('Your first herd');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'listen');
assert.equal(player.querySelector('.conversationCorinEcho').textContent,'Tell me about your first herd.');
assert(box.querySelector('.conversationStage').classList.contains('is-speaking'));
assert(!player.classList.contains('is-speaking'));
assert(player.classList.contains('is-listening'),'Corin’s panel dims while the NPC is speaking');
assert(!box.querySelector('.conversationStage').classList.contains('is-listening'));
assert(box.querySelector('.conversationStage').querySelector('.conversationAdvance').hidden);
assert.equal(run('ask'),null,'Speech continues with no modal ask blocking its clock');
assert.equal(box.style.display,'grid');
assert(run('document.body.classList.contains("topics-open")'));
assert(run('document.body.classList.contains("conversation-speaking")'));
assert(box.querySelectorAll('.deckTopic').every(b=>b.disabled));
assert(box.querySelector('.conversationNext'));
say.scrollHeight=800;say.clientHeight=120;say.scrollTop=50;
dom.dispatch(say,'touchstart',{touches:[{clientX:10,clientY:150}]});
assert.equal(run('lockEl'),say,'The actual dialogue is also a native scroller');
assert(!dom.dispatch(say,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:90}]}).defaultPrevented);
dom.dispatch(say,'touchend');
assert(!box.querySelector('.conversationContinue'));
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'speech');
assert(run('!typeDone()'));
tap(say);assert(run('!typeDone()'),'Full conversations advance only with A, leaving speech free to scroll');
next();assert(run('typeDone()'));assert.equal(run('scene.i'),0,'First A only completes the text');
assert(!box.querySelector('.conversationStage').querySelector('.conversationAdvance').hidden,'Completed speech points to Next');
run('scene.t=1');next();assert(run('ask.replyChoices'),'Second tap offers Corin replies');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'reply');
assert.equal(run('EmberConversationFlow.partner()'),'Hettie','Reply choices preserve the conversation idle');
assert(box.querySelector('.conversationStage').querySelector('.conversationAdvance').hidden,'Reply selection never asks the player to advance a line');
assert.equal(box.style.display,'grid');assert.equal(run('typeWho'),'Hettie','NPC’s line remains while choosing');
assert(!rows.querySelector('.deckTabs'));assert(rows.querySelector('.deckReplyPrompt'));
assert.equal(rows.querySelectorAll('.deckTopic').length,0,'Replies use a distinct menu, not topic cards');
assert.equal(rows.querySelectorAll('.deckReply').length,3);assert(rows.classList.contains('replyMenu'));
assert(player.querySelector('.conversationSpeaker').hidden);
assert.equal(run('ask.opts.filter(o=>!o.head).length'),3,'Three replies stay within the current exchange');
assert(box.querySelector('.conversationGoodbye'),'B remains available while choosing an optional reply');
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'replies');
const waiting=run('scene.i');tap();assert.equal(run('scene.i'),waiting,'Tapping scenery never chooses a reply');
select('Did your aunt want her back?');assert.equal(run('typeWho'),'Corin');
assert.match(run('typeFull'),/aunt/);
assert(player.classList.contains('is-speaking'));assert(!box.querySelector('.conversationStage').classList.contains('is-speaking'));
assert(box.querySelector('.conversationStage').classList.contains('is-listening'),'The NPC panel dims when Corin takes a turn');
assert(!player.classList.contains('is-listening'));
assert.equal(say.parentNode,box.querySelector('.conversationCorinSpeech'),'Corin speaks in the lower lane');
assert.equal(box.querySelector('.conversationPlayer').dataset.mode,'speech');
assert(box.querySelector('.conversationNpcEcho').textContent.length>0,'The NPC’s last words stay above Corin’s response');
assert.equal(box.querySelector('.conversationStage').querySelector('.conversationPortrait').dataset.speaker,'Hettie');
assert(!box.querySelector('.deckReadRing'),'Reply cards do not display a meaningless zero-topic counter');
assert.equal(rows.querySelectorAll('.deckReply').find(n=>n.dataset.selected==='true').dataset.askIndex,3,'The selected reply remains highlighted while it is spoken');assert.equal(box.style.display,'grid');
const autoLine=()=>run(`typeAll();var autoNow=performance.now();for(var frame=0;frame<120;frame++){if(scene)scene.t+=.05;EmberConversationFlow.tick(autoNow+frame*50);}`);
assert(box.querySelector('.conversationPlayer').querySelector('.conversationAdvance').hidden,'Automatic exchanges do not request Next');
autoLine();assert.equal(run('typeWho'),'Hettie');assert.match(run('typeFull'),/visited/);
assert.equal(player.querySelector('.conversationCorinEcho').textContent,'Did your aunt want her back?','Corin’s actual reply remains while the NPC answers');
autoLine();assert.equal(run('ask'),null,'The final NPC answer never times out to the greeting');
assert.match(run('typeFull'),/visited/);
assert(!box.querySelector('.conversationStage').querySelector('.conversationAdvance').hidden,'The final answer asks the player to press Next');
autoLine();assert.equal(run('ask'),null,'Extra reading time leaves the completed exchange visible');
assert.equal(player.querySelector('.conversationCorinEcho').textContent,'Did your aunt want her back?');
next();assert.equal(run('ask.npcConversation'),'Hettie');
assert.equal(box.querySelector('.conversationStage').dataset.phase,'welcome');
assert(!player.classList.contains('is-listening'));assert(!box.querySelector('.conversationStage').classList.contains('is-listening'),'Greeting panels regain full brightness');
assert(!player.querySelector('.conversationSpeaker').hidden);assert(!box.querySelector('.conversationChat').hidden);
assert.equal(player.querySelector('.conversationCorinEcho').textContent,responses.Hettie,'A completed topic restores Corin’s greeting');
assert.equal(run('typeFull'),greetings.Hettie,'A completed topic restores the NPC greeting');
assert(!box.querySelector('.deckHistoryToggle'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
box.querySelector('.conversationChat').onclick({stopPropagation(){}});
// Touch locking must recognize the actual nested scroller, not the full-screen shell.
const workspace=box.querySelector('.conversationWorkspace');
workspace.scrollHeight=1200;workspace.clientHeight=280;workspace.scrollTop=80;
box.scrollHeight=600;box.clientHeight=600;
const card=rows.querySelector('.deckTopic');
dom.dispatch(card,'touchstart',{touches:[{clientX:10,clientY:180}]});
assert.equal(run('lockEl'),workspace,'A drag beginning on a topic locks the inner list');
const drag=dom.dispatch(card,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:100}]});
assert(!drag.defaultPrevented,'The game permits the browser to scroll the topic list');
dom.dispatch(card,'touchend');
box.querySelector('.deckProfileToggle').onclick();
const dossier=box.querySelector('.conversationDossier');
assert(!dossier.hidden);assert.equal(dossier.parentNode,box,'Profile has its own full conversation-sized page');
dossier.scrollHeight=1000;dossier.clientHeight=400;dossier.scrollTop=80;
dom.dispatch(dossier,'touchstart',{touches:[{clientX:10,clientY:180}]});
assert.equal(run('lockEl'),dossier);
assert(!dom.dispatch(dossier,'touchmove',{cancelable:true,touches:[{clientX:10,clientY:100}]}).defaultPrevented);
dom.dispatch(dossier,'touchend');run('askBack()');
// The secondary control returns from replies, then becomes Goodbye at the root.
select('Your first herd');next();run('scene.t=1');next();assert(run('ask.replyChoices'));
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
run("EmberConversationFlow.key({key:'b',preventDefault(){}})");
assert(run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Goodbye');
run("EmberConversationFlow.key({key:'b',preventDefault(){}})");
assert(!run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
run('openNpcTopics(person)');select('Your first herd');
box.querySelector('.conversationGoodbye').onclick({stopPropagation(){}});
assert(!run('EmberConversationFlow.active()'));assert.equal(run('scene'),null);
run('openNpcTopics(person)');
// Every reply remains on this topic, including later topics without bespoke branches.
select('A day off');run('typeAll();scene.t=1');step();
assert.equal(run('ask.opts.filter(o=>!o.head).length'),3);
assert(!run('ask.opts.some(o=>/another question|Tell me about “/.test(o.n))'));
select('What would you do first?');assert.equal(run('typeWho'),'Corin');
autoLine();assert.equal(run('typeWho'),'Hettie');assert.match(run('typeFull'),/breakfast/);
autoLine();assert.equal(run('ask'),null,'Other reply branches also wait at the final answer');
next();assert.equal(run('ask.npcConversation'),'Hettie');assert.equal(run('scene'),null);
// The actual pointer path rejects drags, multi-touch and synthetic click echoes.
select('Your first herd');
dom.dispatch(canvas,'pointerdown');dom.dispatch(canvas,'pointermove',{clientX:30});dom.dispatch(canvas,'pointerup',{clientX:30});dom.dispatch(canvas,'click');
assert(run('!typeDone()'),'Drag never completes dialogue');
dom.dispatch(canvas,'pointerdown');dom.dispatch(canvas,'pointerdown',{pointerId:2,isPrimary:false});dom.dispatch(canvas,'pointerup',{pointerId:2,isPrimary:false});dom.dispatch(canvas,'pointerup');
assert(run('!typeDone()'),'Pinch never completes dialogue');
const ui=dom.element('testButton');ui.tagName='BUTTON';dom.element('stage').append(ui);
tap(ui);assert(run('!typeDone()'),'Unrelated controls do not advance speech through a stage ancestor');
next();assert(run('typeDone()'));assert.equal(run('scene.i'),0);
run('scene.t=1');next();run('askBack()');
// Greeting completion returns to the same NPC; gifts are not bypassed.
select('Hello!');assert(run('sayNpc===person'));
assert(box.querySelector('.conversationGoodbye').disabled,'Required NPC exchanges finish before Goodbye');
next();assert(run('typeDone()'));next();
assert.equal(run('ask.npcConversation'),'Hettie');
run(`askShut();var gifted={n:'Sela',x:100,y:100,d:['Sela: Take care.']};glassShield=true;openNpcTopics(gifted);glassShield=false;`);
select('Hello!');assert.equal(run('ask'),null);finish();
assert(run('glassShield'));assert(run('revealing'));
assert.equal(dom.element('reveal').parentNode,box,'Gift reveal shares the conversation grid, leaving A accessible');
assert(!box.querySelector('.conversationNext').disabled);
assert(box.querySelector('.conversationGoodbye').disabled);assert(!run('EmberConversationFlow.goodbye()'),'Goodbye cannot interrupt a reward');assert.equal(run('ask'),null,'Gift reveal finishes before topics return');
next();assert.equal(run('ask.npcConversation'),'Sela');
// A temporarily full-screen shop returns to the ongoing conversation.
run("drawMerchantShop=()=>{document.getElementById('bagAsk').style.display='none';};askShut();person.sells=true;openNpcTopics(person)");select('Browse your supplies');
assert(run('!!ask.shop'));run('askBack();EmberConversationFlow.tick()');assert.equal(run('ask.npcConversation'),'Hettie','B closes shopping and resumes the conversation');
select('Goodbye');assert.equal(run('ask'),null);assert(!run('EmberConversationFlow.active()'));assert.equal(box.style.display,'none');
assert.equal(run('EmberConversationFlow.partner()'),null,'Goodbye releases the workshop animation');
assert(!say.classList.contains('on'),'Goodbye removes the default dialogue too');
assert.equal(say.parentNode,c.document.body,'Closing full conversation restores the cutscene dialogue overlay');
assert.equal(dom.element('reveal').parentNode,c.document.body,'Gift overlay returns to its normal home too');
run('EmberConversationFlow.prompt(person)');assert(run("ask.opts.some(o=>o.n==='Buy supplies')"),'Merchants offer Talk and Buy before opening either full screen');
select('Buy supplies');assert(run('!!ask.shop'));assert(!run('EmberConversationFlow.active()'));
run('askShut()');
// Ordinary story dialogue gains tapping without creating a conversation panel.
run(`playScene(['Corin: Wait for me.','Hettie: No running.'],{npcActor:person});`);
assert(!run('EmberConversationFlow.active()'),'A story scene does not create a full conversation');
assert.equal(say.parentNode,c.document.body);
tap();assert(run('typeDone()'));assert.equal(run('scene.i'),0);run('scene.t=1');tap();assert.equal(run('scene.i'),1);
run('scene.hold=()=>false;showScene()');tap();assert.equal(run('scene.i'),1,'Cinematic holds cannot be tapped past');
run('scene=null;sayOff()');
// Play a specifically authored alternative for every standard cast member.
const names=JSON.parse(run("JSON.stringify(Object.keys(NPC_TOPIC_GREETINGS).filter(n=>n!=='Aurelius'))"));
assert.equal(names.length,142);
for(const name of names){
 c.speaker=name;
 run(`askShut();scene=null;sayNpc=null;var actor={n:speaker,x:100,y:100,d:['Hello']};var authored=npcStoryTopics(actor).find(t=>t.lines&&t.lines[1]?.startsWith('Corin: '));
 if(!authored)throw Error('Missing story '+speaker);
 ask={quick:1,npcConversation:speaker,npcActor:actor,opts:[{n:'Goodbye'}]};askDraw();
 if(typeWho!==speaker||typeFull!==NPC_TOPIC_GREETINGS[speaker])throw Error('Missing greeting '+speaker);
 EmberConversationFlow.openChat();EmberConversationFlow.take({n:authored.title,go:()=>EmberConversationFlow.playTopic(actor,authored)});typeAll();scene.t=1;EmberConversationFlow.advance();`);
 assert(run('ask?.replyChoices'),name+' gets reply choices');
 assert.equal(run('ask.opts.filter(o=>!o.head).length'),3);
 const reply=JSON.parse(run('JSON.stringify(EmberConversationBranches.choices(scene,scene.i)[0])'));
 select(reply[0]);run('typeAll();scene.t=1');step();
 assert.equal(run('typeFull'),reply[1],name+' answers the selected question');
}
// Aurelius participates too, with distinct responses to personal questions.
run(`askShut();scene=null;sayNpc=null;MAPID='world';dragon.air=false;P.act=null;EmberConversationFlow.prompt(dragon,{dragon:true});`);
assert(!run('EmberConversationFlow.active()'));select('Talk');select('Dragons and our bond');
assert.equal(run('typeFull'),greetings.Aurelius);
assert.equal(dom.element('say').dataset.telepathy,'true','Aurelius greets Corin through the bond');
select('Why did you choose me?');
for(let i=0;i<10&&!run('ask?.replyChoices');i++){run('typeAll();if(scene)scene.t=1');step();}
assert(run('ask?.replyChoices'));assert(run('ask.opts.some(o=>/trying to help/.test(o.n))'));
assert(box.classList.contains('dragonTalk'),'Aurelius’s theme persists through branching replies');
assert.equal(box.querySelector('.conversationGoodbye').textContent,'Back');
const originalLength=run('scene.lines.length');
select('Could you tell I was trying to help?');run('typeAll();scene.t=1');step();assert.equal(run('typeWho'),'Aurelius');assert.match(run('typeFull'),/Asking Maddock/);
assert.equal(run('scene.lines.length'),originalLength,'An early alternate preserves the later conversation');
let laterChoices=0;
for(let i=0;i<40&&run('!!scene');i++){
 if(run('ask?.replyChoices')){assert.equal(run('ask.opts.filter(o=>!o.head).length'),3);select(run('ask.opts.filter(o=>!o.head)[1].n'));laterChoices++;}
 else{run('typeAll();if(scene)scene.t=1');step();}
}
assert.equal(laterChoices,3,'All three subsequent reply points survive an early alternative');
assert.equal(run('ask.topicScope'),'dragons');
// Changing area / loading another scene cannot resurrect an old conversation.
run(`MAPID='house0';EmberConversationFlow.tick()`);assert(!run('EmberConversationFlow.active()'));assert.equal(run('ask'),null);
console.log('PASS: persistent parchment, actual tap/drag/pinch routing, authored choices for 142 NPCs and Aurelius, branching responses, root/branch Back, greetings, gifts, shopping and area teardown.');
run(`const showdownKing={n:'King Halvard',x:100,y:100};ask=null;`);
for(const map of ['cinderhold','world']){
 c.kingMap=map;run('MAPID=kingMap');
 assert.equal(run('EmberConversationFlow.prompt(showdownKing)'),false,'King uses scripted dialogue outside the tavern');
 assert.equal(run('openNpcTopics(showdownKing)'),false,'No expanded king topics outside the tavern');
 assert.equal(run('ask'),null,'No conversation menu replaces the showdown');
}
run("MAPID='tavern'");
assert.equal(run('EmberConversationFlow.prompt({...showdownKing,thornwellRoyal:true})'),true,'Tavern royal audience retains its prompt');
run('askShut()');
console.log('PASS: expanded king conversation is restricted to the tavern; final showdown remains scripted.');
