import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run,context:c}=await loadEditorGame(process.cwd(),{log(){},warn(){}},{furniture:false});
c.CraftingView=undefined;
const json=expr=>JSON.parse(run('JSON.stringify('+expr+')'));
const reset=()=>run(`Crafting.close();Crafting.restore(null);mode='play';gameplayStarted=true;quest=Q.DONE;bagOwned=true;
 MAPID='house26';MD=W.maps.house26;scene=null;sayNpc=null;revealing=false;fadeDir=0;doorMotion=null;
 trial=null;arenaLock=null;deadShown=false;mounted=false;ride=null;fishing=null;P.act=null;flightTravel=null;
 foes=[];ask=null;ovl=null;templeCompass.morningMet=true;potions=0;elixirs=0;bombs=0;dust=0;bells=0;marks=0;breaths=0;stones=0;salts=0;
 boarMeat=5;hareMeat=5;deerMeat=5;foxMeat=5;birdMeat=5;dragonFish=5;`);
reset();
assert(run('Crafting.open()'));assert.equal(run('Crafting.maxBatch(Crafting.recipe("potion"))'),3);
run('Crafting.learn("nan",true);Crafting.close();Crafting.open()');
assert.equal(run('Crafting.count("herb")'),6,'Starter ingredients granted only once');
assert(!run('Crafting.start("stone")'),'Unknown recipe stays locked');
assert(!run('Crafting.start("potion",4)'),'Insufficient ingredients cannot be spent');
const ids=json('Crafting.recipes.map(r=>r.id)');assert.equal(ids.length,15);
for(const id of ids){
 reset();run('Crafting.skip();Crafting.open()');
 const recipe=json(`Crafting.recipe('${id}')`),before=json(`Object.fromEntries(Object.keys(Crafting.recipe('${id}').cost).map(k=>[k,Crafting.count(k)]))`),held=run(`Crafting.count('${id}')`);
 assert(run(`Crafting.start('${id}',2,true)`));
 for(const [k,n] of Object.entries(recipe.cost))assert.equal(run(`Crafting.count('${k}')`),before[k]-n*2);
 run('Crafting.press();Crafting.press();Crafting.press()');
 assert.equal(run(`Crafting.count('${id}')`),held+3,'Successful timing produces batch plus one: '+id);
 assert.equal(run('Crafting.capture().pending'),null);
 run('Crafting.press();Crafting.close()');assert.equal(run(`Crafting.count('${id}')`),held+3,'Finished reward cannot duplicate or refund');
}
reset();run('Crafting.skip();Crafting.open();Crafting.start("potion");Crafting.tick(.05);Crafting.current().meter=0;Crafting.press()');
assert.equal(run('Crafting.current().phase'),'heat');
run('Crafting.press();Crafting.tick(.05)');assert(run('Crafting.current().heat>.45'),'Holding warms');
run('Crafting.release();Crafting.tick(.05)');assert(!run('Crafting.current().held'));
c.document.hidden=true;const paused=run('Crafting.current().time');run('Crafting.tick(.05)');assert.equal(run('Crafting.current().time'),paused);c.document.hidden=false;
run('for(let i=0;i<125;i++)Crafting.tick(.05);Crafting.current().meter=0;Crafting.press()');
assert.equal(run('potions'),1,'Missed timing still produces ordinary item');
reset();run('Crafting.open();Crafting.start("potion",2);Crafting.close();Crafting.close()');
assert.equal(run('Crafting.count("herb")'),6,'Cancel refunds exactly once');assert.equal(run('potions'),0);
reset();run('Crafting.open();Crafting.start("cooked_dragonFish",2);saveToSlot(1,true)');
assert.equal(run('dragonFish'),3);
assert(run('loadGame(1)'),'Actual game load succeeds');assert.equal(run('dragonFish'),5,'Interrupted food batch refunds raw fish after base inventory loads');
assert.equal(run('Crafting.count("herb")'),6);assert.equal(run('Crafting.capture().pending'),null);assert(!run('Crafting.active()'));
run('saveToSlot(1,true);loadGame(1)');assert.equal(run('dragonFish'),5,'Refund persists without duplication');
run('localStorage.setItem(saveKey(2),JSON.stringify({...captureSave(),crafting:undefined}));loadGame(2)');
assert.equal(run('Crafting.count("herb")'),0,'Legacy and other save slots do not inherit supplies');
reset();run('Crafting.skip();Crafting.open();Crafting.start("potion",1,true);Crafting.press();Crafting.press();Crafting.press();saveToSlot(1,true);loadGame(1)');
assert.equal(run('potions'),2,'Completed batch persists');assert.equal(run('Crafting.count("herb")'),18,'Completed costs stay spent');
reset();
for(const [n,group,packSpr] of [['Nan Ferrow','nan'],['Wren','healer'],['The Shroom King','shroom'],['Dunstan','smith'],['Brother Edrin','chapel','chapel_priest'],['Maelis','witch'],['Sverre','winter']]){
 run(`scene=null;sayNpc=null;Crafting.close();Crafting.restore({starter:true});var teacher={n:${JSON.stringify(n)},packSpr:${JSON.stringify(packSpr)},x:100,y:100};var topic=npcStoryTopics(teacher).find(t=>t.title==='Will you teach me to craft?');`);
 assert(run('!!topic'),n+' has recipe topic in actual conversation');
 run('topic.go();var finishLesson=scene.after;scene=null;sayNpc=null;finishLesson()');
 assert(run(`Crafting.capture().learned.includes('${group}')`));assert(run('Crafting.active()'),n+' opens book after lesson');
}
reset();run('Crafting.open({n:"Wren"});gold=100;breathHas.lightning=false;breathHas.ice=false;wonAll=0');
assert(!run('Crafting.buy("snowbell")'),'Late ingredients not sold early');assert(!run('Crafting.buy("essence")'),'Rare essence cannot be bought');
assert(run('Crafting.buy("herb")'));assert.equal(run('gold'),94);
run('breathHas.lightning=true;breathHas.ice=true');assert(run('Crafting.buy("snowbell")'));assert.equal(run('gold'),79);
run('gold=0');assert(!run('Crafting.buy("herb")'));
reset();run('Crafting.skip();dragonOff=false;dragon.on=true;syncDragonVitality(false);dragon.hp=1;dragon.down=false');
for(const id of ids.filter(id=>id.startsWith('cooked_'))){assert(run(`USABLE['${id}']&&HEALS['${id}']!==undefined&&BAG.some(it=>it.key==='${id}'&&it.has())`));}
assert(run('Crafting.useFood("cooked_boarMeat")'));assert.equal(run('dragon.hp'),run('Math.min(dragon.maxHp,41)'));
run('dragon.hp=dragon.maxHp');assert(!run('Crafting.useFood("cooked_boarMeat")'));
run('dragon.hp=0;dragon.down=true;dragon.revive=100');assert(run('Crafting.useFood("cooked_dragonFish")'));assert.equal(run('dragon.revive'),1.2);
reset();run('var defeated={kind:"golem1",hp:0,st:"dead"};Crafting.defeated(defeated);Crafting.defeated(defeated)');
assert.equal(run('Crafting.count("mineral")'),2);
run('Crafting.defeated({kind:"lich",hp:0,ally:true});Crafting.defeated({kind:"ghost",hp:1});Crafting.defeated({kind:"ghost",hp:0,storyKnight:true});Crafting.defeated({kind:"ghost",hp:0,huntingArena:1})');
assert.equal(run('Crafting.count("essence")'),0);
run('Crafting.defeated({kind:"icemoth",hp:0});Crafting.defeated({kind:"lich",hp:0})');assert.equal(run('Crafting.count("essence")'),2);
run(`houseLootTaken.clear();MD={roomActors:[{x:100,y:100,houseLoot:{id:'craft-chest',gold:7}}]};P.x=100;P.y=124;tryHouseLootChest()`);
const rewardTotal=run('Object.values(Crafting.capture().ingredients).reduce((a,b)=>a+b,0)');run('tryHouseLootChest()');
assert.equal(run('Object.values(Crafting.capture().ingredients).reduce((a,b)=>a+b,0)'),rewardTotal);
assert.match(run('lootChestAnimations.get("craft-chest").caption'),/\+2 (Healing Herb|Mineral Dust)/);
reset();run('mounted=true');assert(!run('Crafting.open()'));run('mounted=false;fishing={}');assert(!run('Crafting.open()'));
reset();run("MAPID='world';MD=W.maps.world;Crafting.inspect().nodes.splice(0);Crafting.inspect().nodes.push({id:'craft:test:0',material:'snowbell',x:100,y:100});P.x=100;P.y=124;bossScene=null;foesHeld=true");
assert(run('Crafting.gather()'),'A gathers from any side');assert.equal(run('Crafting.count("snowbell")'),2);
assert(!run('Crafting.gather()'),'Patch cannot be collected twice during cooldown');
run('var harvestedSave=Crafting.capture();Crafting.restore(harvestedSave)');assert(!run('Crafting.gather()'),'Cooldown survives restoring saved data');
reset();run("Crafting.open({n:'Wren'});EmberConversationFlow.tick()");assert.equal(run('ask'),null,'Closing a shop for crafting does not reopen a conversation');
console.log('PASS: all 15 recipes, timing and steady modes, rewards, cancellations, actual saves, seven NPC teachers, merchants, cooked food and once-only drops.');
