import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run,context:c}=await loadEditorGame(process.cwd(),{log(){},warn(){}},{furniture:false});
c.CraftingView=undefined;
const json=expr=>JSON.parse(run('JSON.stringify('+expr+')'));
const reset=()=>run(`Crafting.close();Crafting.restore(null);mode='play';gameplayStarted=true;quest=Q.DONE;bagOwned=true;
 MAPID='house26';MD=W.maps.house26;scene=null;sayNpc=null;revealing=false;fadeDir=0;doorMotion=null;
 trial=null;arenaLock=null;deadShown=false;mounted=false;ride=null;fishing=null;P.act=null;flightTravel=null;
 foes=[];ask=null;ovl=null;templeCompass.morningMet=true;templeCompass.meatGiven=true;Crafting.giveKit();Crafting.restore({...Crafting.capture(),learned:[]});potions=0;elixirs=0;bombs=0;dust=0;bells=0;marks=0;breaths=0;stones=0;salts=0;
 boarMeat=5;hareMeat=5;deerMeat=5;foxMeat=5;birdMeat=5;dragonFish=5;`);
const animate=()=>run('for(let i=0;i<91;i++)Crafting.tick(.05)');
const solve=()=>{run('Crafting.slide(1);Crafting.finish()');animate();};
reset();assert(run('Crafting.open()'));assert.equal(run('Crafting.capture().learned.length'),0,'Opening a book cannot grant unlearned recipes');
assert(!run('Crafting.start("potion")'),'No recipe, no crafting');
run('Crafting.learn("nan",true);Crafting.learn("nan",true)');assert.equal(run('Crafting.count("herb")'),0,'Lessons do not duplicate the trail supplies');
assert(!run('Crafting.start("stone")'));assert(!run('Crafting.start("potion")'),'Missing ingredients');
const ids=json('Crafting.recipes.map(r=>r.id)');assert.equal(ids.length,15);
for(const id of ids){
 reset();run('Crafting.skip();Crafting.open()');
 const recipe=json(`Crafting.recipe('${id}')`),before=json(`Object.fromEntries(Object.keys(Crafting.recipe('${id}').cost).map(k=>[k,Crafting.count(k)]))`),held=run(`Crafting.count('${id}')`);
 assert(run(`Crafting.start('${id}',2)`));
 for(const [k,n] of Object.entries(recipe.cost))assert.equal(run(`Crafting.count('${k}')`),before[k]-n*2);
 assert(!run('Crafting.finish()'),'Unfinished preparation cannot award items');
 c.document.hidden=true;run('for(let i=0;i<100;i++)Crafting.tick(.05)');assert.equal(run('Crafting.current().progress'),0,'Hidden pages pause the animation');c.document.hidden=false;
 run('Crafting.slide(1);Crafting.finish()');assert.equal(run('Crafting.current().phase'),'crafting');
 assert.equal(run('Crafting.current().duration'),4.5,'All recipes use a 4.5-second preparation');
 assert.equal(run(`Crafting.count('${id}')`),held,'No reward until the animation finishes');
 assert(!run('Crafting.finish()'),'Repeated confirmation cannot skip the animation');
 c.document.hidden=true;animate();assert.equal(run('Crafting.current().age'),0,'Hidden pages pause confirmed crafting');c.document.hidden=false;
 run('for(let i=0;i<89;i++)Crafting.tick(.05)');assert.equal(run(`Crafting.count('${id}')`),held,'No early reward before 4.5 seconds');
 animate();assert.equal(run('Crafting.current().phase'),'result');assert(!run('Crafting.finish()'));
 assert.equal(run(`Crafting.count('${id}')`),held+2,'Exact requested batch, no extra potion from one set of materials');
 assert.equal(run('Crafting.capture().pending'),null);
 run('Crafting.press();Crafting.close()');assert.equal(run(`Crafting.count('${id}')`),held+2);
}
reset();run('Crafting.skip();Crafting.open();Crafting.start("potion",2);Crafting.slide(1);Crafting.finish();Crafting.tick(.05);Crafting.close();Crafting.close()');
assert.equal(run('Crafting.count("herb")'),20,'Cancel refunds exactly once');assert.equal(run('potions'),0);
reset();run('Crafting.skip();Crafting.open();Crafting.start("cooked_dragonFish",2);Crafting.slide(1);Crafting.finish();Crafting.tick(.05);saveToSlot(1,true)');
assert.equal(run('dragonFish'),3);assert(run('loadGame(1)'));assert.equal(run('dragonFish'),5,'Interrupted batch refunds raw fish');
assert.equal(run('Crafting.count("herb")'),20);assert.equal(run('Crafting.capture().pending'),null);
run('saveToSlot(1,true);loadGame(1)');assert.equal(run('dragonFish'),5);
run('localStorage.setItem(saveKey(2),JSON.stringify({...captureSave(),crafting:undefined}));loadGame(2)');
assert.equal(run('Crafting.count("herb")'),0,'Legacy slots do not inherit supplies');
reset();run('Crafting.skip();Crafting.open();Crafting.start("potion")');solve();run('Crafting.finish();saveToSlot(1,true);loadGame(1)');
assert.equal(run('potions'),1);assert.equal(run('Crafting.count("herb")'),18);
for(const steps of [0,1,3]){
 reset();run('Crafting.skip();Crafting.open();Crafting.start("potion",3)');
 run('for(let i=0;i<'+(steps*20)+';i++)Crafting.tick(.05)');
 assert(!run('Crafting.finish()'),'Waiting cannot craft');run('Crafting.slide(.5)');assert(!run('Crafting.finish()'));run('Crafting.release()');assert.equal(run('Crafting.current().progress'),0);run('Crafting.slide(1)');assert(run('Crafting.finish()'),'Full slide crafts');
 assert(!run('Crafting.finish()'),'Repeated confirmation cannot duplicate rewards');animate();
 assert.equal(run('potions'),3);assert.equal(run('Crafting.count("herb")'),14);
 assert.equal(run('Crafting.count("root")'),17);assert.equal(run('Crafting.capture().pending'),null);
}
reset();assert(!run('Crafting.finish()'));run('Crafting.skip();Crafting.open();Crafting.start("potion");Crafting.cancel()');assert(!run('Crafting.finish()'));
reset();run('Crafting.skip();Crafting.open();Crafting.start("potion")');
run('Crafting.tick(NaN);Crafting.tick(-1)');assert.equal(run('Crafting.current().progress'),0);
reset();
for(const [n,group,packSpr] of [['Nan Ferrow','nan'],['Wren','healer'],['The Shroom King','shroom'],['Dunstan','smith'],['Brother Edrin','chapel','chapel_priest'],['Maelis','witch'],['Sverre','winter']]){
 run(`scene=null;sayNpc=null;Crafting.close();Crafting.restore({starter:true});var teacher={n:${JSON.stringify(n)},packSpr:${JSON.stringify(packSpr)},x:100,y:100};var topic=npcStoryTopics(teacher).find(t=>t.title==='Will you teach me to craft?');`);
 assert(run('!!topic'),n+' has recipe topic in actual conversation');
 run('topic.go();var finishLesson=scene.after;scene=null;sayNpc=null;finishLesson()');
 assert(run(`Crafting.capture().learned.includes('${group}')`));assert(run('Crafting.active()'),n+' opens book after lesson');
}
reset();run('Crafting.open({n:"Wren"});gold=100;breathHas.lightning=false;breathHas.ice=false;wonAll=0');
assert(!run('Crafting.buy("snowbell")'),'Late ingredients not sold early');assert(!run('Crafting.buy("essence")'),'Rare essence cannot be bought');
assert(run('Crafting.buy("herb")'));assert.equal(run('gold'),94);
run('breathHas.lightning=true;breathHas.ice=true');assert(run('Crafting.buy("snowbell")'));assert.equal(run('gold'),79);
run('gold=0');assert(!run('Crafting.buy("herb")'));
reset();run('Crafting.skip();dragonOff=false;dragon.on=true;syncDragonVitality(false);dragon.hp=1;dragon.down=false');
for(const id of ids.filter(id=>id.startsWith('cooked_'))){assert(run(`USABLE['${id}']&&HEALS['${id}']!==undefined&&BAG.some(it=>it.key==='${id}'&&it.has())`));}
assert(run('Crafting.useFood("cooked_boarMeat")'));assert.equal(run('dragon.hp'),run('Math.min(dragon.maxHp,41)'));
run('dragon.hp=dragon.maxHp');assert(!run('Crafting.useFood("cooked_boarMeat")'));
run('dragon.hp=0;dragon.down=true;dragon.revive=100');assert(run('Crafting.useFood("cooked_dragonFish")'));assert.equal(run('dragon.revive'),1.2);
reset();run('var defeated={kind:"golem1",hp:0,st:"dead"};Crafting.defeated(defeated);Crafting.defeated(defeated)');
assert.equal(run('Crafting.count("mineral")'),2);
run('Crafting.defeated({kind:"lich",hp:0,ally:true});Crafting.defeated({kind:"ghost",hp:1});Crafting.defeated({kind:"ghost",hp:0,storyKnight:true});Crafting.defeated({kind:"ghost",hp:0,huntingArena:1})');
assert.equal(run('Crafting.count("essence")'),0);
run('Crafting.defeated({kind:"icemoth",hp:0});Crafting.defeated({kind:"lich",hp:0})');assert.equal(run('Crafting.count("essence")'),2);
run(`houseLootTaken.clear();MD={roomActors:[{x:100,y:100,houseLoot:{id:'craft-chest',gold:7}}]};P.x=100;P.y=124;tryHouseLootChest()`);
const rewardTotal=run('Object.values(Crafting.capture().ingredients).reduce((a,b)=>a+b,0)');run('tryHouseLootChest()');
assert.equal(run('Object.values(Crafting.capture().ingredients).reduce((a,b)=>a+b,0)'),rewardTotal);
assert.match(run('lootChestAnimations.get("craft-chest").caption'),/\+2 (Healing Herb|Mineral Dust)/);
reset();run('mounted=true');assert(!run('Crafting.open()'));run('mounted=false;fishing={}');assert(!run('Crafting.open()'));
reset();run("MAPID='world';MD=W.maps.world;Crafting.inspect().nodes.splice(0);Crafting.inspect().nodes.push({id:'craft:test:0',material:'snowbell',x:100,y:100});P.x=100;P.y=124;bossScene=null;foesHeld=true");
assert(run('Crafting.gather()'),'A gathers from any side');assert.equal(run('Crafting.count("snowbell")'),2);
assert(!run('Crafting.gather()'),'Patch cannot be collected twice during cooldown');
run('var harvestedSave=Crafting.capture();Crafting.restore(harvestedSave)');assert(!run('Crafting.gather()'),'Cooldown survives restoring saved data');
reset();run("MAPID='world';MD=W.maps.world;Crafting.inspect().nodes.splice(0);Crafting.inspect().nodes.push({id:'craft:intro:herb',material:'herb',amount:2,once:true,x:100,y:100},{id:'craft:intro:root',material:'root',amount:1,once:true,x:200,y:100});bossScene=null;foes=[];P.x=100;P.y=100;Crafting.gather();P.x=200;Crafting.gather();");
assert.equal(run('Crafting.count("herb")'),2);assert.equal(run('Crafting.count("root")'),1);
run('Crafting.restore(Crafting.capture())');assert(!run('Crafting.gather()'),'One-time trail supplies stay harvested after reload');
assert.equal(run('Crafting.capture().harvested["craft:intro:root"]'),-1);
run('Crafting.learn("nan",true);Crafting.open()');assert.equal(run('Crafting.maxBatch(Crafting.recipe("potion"))'),1);
assert(run('Crafting.start("potion")'));solve();assert.equal(run('Crafting.current().phase'),'result');assert.equal(run('potions'),1);
assert.equal(run('Crafting.maxBatch(Crafting.recipe("potion"))'),0,'Northern trail supplies make exactly one potion');
reset();run("Crafting.open({n:'Wren'});EmberConversationFlow.tick()");assert.equal(run('ask'),null,'Closing a shop for crafting does not reopen a conversation');
reset();run('templeCompass.meatGiven=false;Crafting.restore(null)');assert(!run('Crafting.open()'));run('nanGiftBeat(14)');assert(run('Crafting.hasKit()'));const meat=run('hareMeat');run('nanGiftBeat(14)');assert.equal(run('hareMeat'),meat);run('Crafting.restore(Crafting.capture())');assert(run('Crafting.hasKit()'));
console.log('PASS: all 15 recipes, slide confirmation, delayed rewards, hidden-page pause, cancellations and refunds, actual saves, seven NPC teachers, merchants, cooked food and once-only drops.');
