import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run,context}=await loadEditorGame(process.cwd(),{log(){},warn(){},error:console.error},{furniture:false});
context.assert=assert;
run(`
let rescueScenes=[],rescueSaves=0;
playScene=(lines,options)=>rescueScenes.push({lines,options});saveGame=()=>{rescueSaves++;};
sayOff=()=>{};faceToward=()=>{};toast=()=>{};openNpcTopics=()=>{};
quest=Q.DONE;brambleQuest=2;wonAll=0;houseLootTaken.clear();
const campMap={npcs:[],roomActors:[],roomBlocks:[]};
HollybeckRescue.installWorld(campMap);HollybeckRescue.installWorld(campMap);
assert.equal(campMap.npcs.length,2);assert.equal(campMap.roomActors.length,1);assert.equal(campMap.roomBlocks.length,1);
assert.equal(HollybeckRescue.known(),false);
const lead=HollybeckRescue.topics({n:'Astrid'})[0];lead.go();
assert(HollybeckRescue.known());assert(rescueScenes.at(-1).lines.some(s=>s.includes('Sandspire')));
assert(!/moth|creature|monster/i.test(rescueScenes.at(-1).lines.join(' ')),'Astrid does not know about or spoil the threat');
assert(!/moth/i.test(JSON.stringify(HollybeckRescue.quests())),'Initial journal preserves the surprise');
assert(!/moth/i.test(JSON.stringify(atlasQuestStages({id:'winter-rescue'}))),'Checklist preserves the surprise');
assert(atlasQuestOptions().some(q=>q.id==='winter-rescue'));
const olin=campMap.npcs[0];houseLootTaken.add('world:ice-moth:soulwing');
HollybeckRescue.talk(olin);rescueScenes.at(-1).options.after();
assert(!HollybeckRescue.rescued(),'Skip or owning the relic does not rescue the party');
assert.equal(atlasQuestTarget({id:'winter-rescue'}).y,168*16);
IceMoth.defeated();assert(!HollybeckRescue.rescued(),'Victory alone still requires speaking to a traveler');
assert.equal(atlasQuestTarget({id:'winter-rescue'}).y,135*16);
HollybeckRescue.talk(campMap.npcs[1]);
assert(!HollybeckRescue.rescued(),'The rescue is recorded after the reassurance dialogue');
rescueScenes.at(-1).options.after();assert(HollybeckRescue.rescued());
assert(atlasQuestComplete('winter-rescue'));assert(!atlasQuestOptions().some(q=>q.id==='winter-rescue'));
assert(atlasCompletedEntries().some(q=>q.id==='winter-rescue'));
const saved=[...houseLootTaken];houseLootTaken.clear();assert(!HollybeckRescue.rescued());
for(const key of saved)houseLootTaken.add(key);assert(HollybeckRescue.rescued(),'Existing save ledger restores progress');
const count=rescueSaves;HollybeckRescue.talk(olin);rescueScenes.at(-1).options.after();assert.equal(rescueSaves,count,'Repeated greetings cannot award completion twice');
HollybeckRescue.topics({n:'Sverre'})[0].go();assert(HollybeckRescue.frostKnown());
assert(atlasQuestOptions().some(q=>q.id==='frosthorn'));
assert.equal(atlasQuestTarget({id:'frosthorn'}).x,2545*16);
assert(HollybeckRescue.topics({n:'Astrid'})[0].title.includes('safe'));
houseLootTaken.clear();dragonBanterSeen.clear();breathHas.shadow=false;MAPID='world';
areaUnder=()=> 'Hollybeck';revealing=null;chestAnim=null;
assert.equal(FrostcragJourney.step(),false,'No mountain briefing before snow temple');
breathHas.shadow=true;breathHas.ice=true;breathHas.lightning=true;smithUpgrade=true;charm.edge=true;glassShield=true;
assert(FrostcragJourney.step());assert.equal(rescueScenes.at(-1).options.who,'Aurelius');
assert(!/ashfiend/i.test(rescueScenes.at(-1).lines.join(' ')));
assert(rescueScenes.at(-1).lines.some(s=>s.includes('Ashcrag')));
rescueScenes.at(-1).options.after();assert.equal(FrostcragJourney.step(),false,'Briefing is once per save');
assert.equal(atlasJourneyObjective().questId,'highland-passage');
assert(FrostcragJourney.target(),'The tracked destination is the real cave entrance');
areaUnder=()=> 'Ashcrag';FrostcragJourney.step();assert(FrostcragJourney.arrived());
assert.equal(atlasJourneyObjective().title,'Face King Halvard');
`);
console.log('PASS: both Hollybeck leads, rescue before/after victory, Skip safety, journal stages/targets, save-ledger replay, one-time completion and post-temple Frostcrag briefing.');
