import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run,context:c}=await loadEditorGame(process.cwd(),{log(){},warn(){}});
await run('loadPublishedEditorLayouts();prepareNanCookingArt()');
run(`quest=Q.DONE;restoreFatherCompass(null);loadMap('house26');`);
assert(!run("npcs.find(n=>n.n==='Nan Ferrow').nanCooking"),'Nan waits for the farewell gift before cooking');
run(`restoreFatherCompass({owned:true,mapGiven:true,meatGiven:true});loadMap('house26');var nan=npcs.find(n=>n.n==='Nan Ferrow');P.x=182;P.y=177;`);
assert(run("nan.nanCooking&&nan.packSpr==='nan_cooking'&&nan.stationary"));
assert.equal(run('SPR.nan_cooking[4]'),12);assert.equal(run('SPR.nan_cooking[3]'),57);
assert(run('canStand(P.x,P.y)&&nearestTalkNpc()===nan'),'Corin can stand at talking distance');assert(run('blockedByNpcBody(170,145)'),'Cauldron has a solid body');
for(const [dx,dy] of [[0,17],[0,-49],[-29,-17],[29,-17]]){run('P.x=nan.x+'+dx+';P.y=nan.y+'+dy);assert(run('canStand(P.x,P.y)'), 'All four approaches are walkable');assert(run('nearestTalkNpc()===nan'),'Nan talks from every side of the cauldron');}
let now=1000000,saves=0,reveal=null;c.clock=()=>now;run('Date.now=clock');
c.saveGame=()=>saves++;c.showReveal=(...args)=>reveal=args;c.openNpcTopics=()=>{};
const finish=()=>run('var after=scene.after;scene=null;after()');
run('elixirs=0;gold=123;restoreNanCooking(null);giveNanElixir(nan)');
assert.equal(run('elixirs'),0,'Reward waits for the exchange');finish();
assert.equal(run('elixirs'),1);assert.equal(run('nanElixirReadyAt'),now+600000);assert.equal(saves,1);assert.equal(reveal[0],'inventory_elixir');assert.equal(run('gold'),123);
const saved=run('captureSave().nanElixirReadyAt');
run('restoreNanCooking(0);restoreNanCooking('+saved+');giveNanElixir(nan)');assert.match(run('scene.lines[0]'),/10 minutes/);finish();assert.equal(run('elixirs'),1);
now+=599999;run('giveNanElixir(nan)');finish();assert.equal(run('elixirs'),1);
now++;run('giveNanElixir(nan)');finish();assert.equal(run('elixirs'),2);assert.equal(saves,2);
run('restoreFatherCompass(null);loadMap("house26")');
assert(!run("npcs.find(n=>n.n==='Nan Ferrow').nanCooking"),'Loading a pre-gift save restores Nan');
console.log('PASS: original twelve-frame cauldron animation, talkable placement, solid cauldron, free elixir once per ten minutes, saved cooldown and pre-gift restoration.');
