import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
import {gameDom} from './helpers-game-dom.mjs';

const dom=gameDom(),{run,context:c}=await loadEditorGame(process.cwd(),{log(){},warn(){}},{document:dom.document,furniture:false});
const el=dom.element,click=id=>dom.dispatch(el(id),'click');
const header=c.document.createElement('header');header.append(el('atlasClose'));el('worldAtlas').append(header,el('atlasBody'),el('atlasQuestsScreen'));
el('atlasBody').append(el('atlasDetails'));el('atlasDetails').append(el('atlasQuests'));
el('atlasQuestsScreen').append(el('atlasQuestsBack'),el('atlasQuestsClose'),el('atlasQuestList'),el('atlasQuestInfo'));
el('atlasQuestList').className='scrolls';el('atlasQuestInfo').className='scrolls';
el('atlasQuestList').append(el('atlasActiveQuests'),el('atlasCompletedQuests'));el('atlasQuestInfo').append(el('atlasFocus'));
let saved,notice='',now=1000;
c.saveGame=()=>saved=JSON.parse(run('JSON.stringify(captureQuestJournal())'));
c.toast=text=>notice=text;c.performance={now:()=>now};
run(`gameplayStarted=true;mode='play';MAPID='world';MD=W.maps.world;P.x=30*TS;P.y=425*TS;
quest=Q.DONE;dragon.on=true;dragonIntroDone=true;dragonOff=false;EmberRiding.skip();
templeCompass.owned=true;templeCompass.mapGiven=true;atlasCompassTutorialSeen=true;
odoRodReferral=true;fishingPole=false;atlasTrackedQuest='fishing';openAtlas();`);
assert(run('atlasOpen'));assert(!run('atlasJournalOpen'));assert(el('atlasQuestsScreen').hidden);
assert.equal(el('atlasName').textContent,'Millwood','Map opens on the current area, not the remote quest');
assert.equal(el('atlasAreaLabel').textContent,'YOUR CURRENT AREA');
assert.equal(el('atlasTrackedTitle').textContent,'Calder’s spare rod');
const sandspire=el('atlasPlaces').children.find(b=>b.textContent==='Sandspire');
sandspire.onclick({stopPropagation(){},detail:0});
assert.equal(el('atlasName').textContent,'Sandspire');assert.equal(el('atlasAreaLabel').textContent,'SELECTED AREA');
assert.equal(el('atlasTrackedTitle').textContent,'Calder’s spare rod','Area selection preserves the tracked summary');
click('atlasQuests');assert(run('atlasJournalOpen'));assert(el('atlasBody').hidden);assert(header.hidden);
assert.equal(el('atlasQuestTitle').textContent,'Calder’s spare rod');
assert(!el('atlasFocus').hidden);assert(!el('atlasFocus').disabled);
const active=id=>el('atlasActiveQuests').children.find(b=>b.dataset.questId===id);
active('main').onclick();assert.equal(run('atlasSelectedQuest'),'main');
assert.equal(run('atlasTrackedQuest'),'fishing','Browsing never changes the compass');
assert.equal(saved,undefined,'Browsing never saves a tracking change');
click('atlasQuestsBack');assert(!run('atlasJournalOpen'));assert(run('atlasOpen'));
assert.equal(el('atlasName').textContent,'Sandspire','Back preserves the selected map area');
run('closeAtlas();openAtlas()');assert.equal(el('atlasName').textContent,'Millwood','Reopening resets the area to Corin');
// Tracking from inventory must resume gameplay instead of reopening the bag.
run("closeAtlas();openAtlas('bag')");click('atlasQuests');active('main').onclick();
run('keys.ArrowUp=1;padDx=1;padDy=1');click('atlasFocus');
assert(!run('atlasOpen'));assert(!run('atlasJournalOpen'));assert(!run('bagOpen'));assert.equal(run('ovl'),null);
assert.equal(el('worldAtlas').style.display,'none');assert.equal(run('atlasTrackedQuest'),'main');
assert.equal(saved.tracked,'main');assert(saved.compassTutorialSeen);assert.match(notice,/Tracking quest:.*follow the compass/);
assert.equal(run('keys.ArrowUp'),0);assert.equal(run('padDx+padDy'),0);
assert.equal(run('fishingPole'),false,'Tracking grants no quest rewards');
assert.equal(run('compassTrackingStarted'),now,'The visible compass animation begins after closing the map');
const motion=t=>run(`compassTrackingMotion(${t})`);
assert(motion(now).glow>0);assert(motion(now+700).spin>Math.PI,'The needle visibly spins');
assert(motion(now+1700).wiggle>0);assert(motion(now+1900).wiggle<0,'The settle wiggle changes direction');
assert(motion(now+2200).glow>0);
assert.deepEqual(JSON.parse(JSON.stringify(motion(now+2800))),{spin:0,wiggle:0,glow:0},'Animation ends exactly at the live bearing');
assert.equal(run('compassTrackingStarted'),null);
c.matchMedia=()=>({matches:true});now=6000;run('compassCelebrateTracking()');
assert.equal(motion(now+400).spin,0);assert.equal(motion(now+400).wiggle,0);assert(motion(now+400).glow>0,'Reduced motion keeps a gentle glow');
motion(now+1400);assert.equal(run('compassTrackingStarted'),null);c.matchMedia=()=>({matches:false});
// Completed quests remain readable but cannot be tracked; unknown IDs are rejected.
run('fishingPole=true;openAtlas()');click('atlasQuests');
const completed=el('atlasCompletedQuests').children.find(b=>b.dataset.questId==='fishing');
assert(completed);completed.onclick();assert.equal(el('atlasQuestTitle').textContent,'Calder’s spare rod');
assert.match(el('atlasObjective').textContent,/Received/);assert(el('atlasFocus').hidden);assert(el('atlasFocus').disabled);
assert.equal(run("atlasTrack('fishing')"),false);assert.equal(run("atlasTrack('unknown')"),false);assert(run('atlasOpen'));
run('actionButton()');assert(run('atlasOpen'),'A does not track a completed quest');
run('atlasTimer=0;atlasMove(0,-1)');assert(!run('atlasSelectedComplete'),'D-pad selects another quest instead of moving the hidden map');
run("atlasChooseQuest('temple:Forgewick');actionButton()");assert(!run('atlasOpen'),'A tracks the selected available quest');
run('openAtlas();atlasOpenJournal();atlasBack()');assert(!run('atlasJournalOpen'));assert(run('atlasOpen'));
run('atlasBack()');assert(!run('atlasOpen'),'B backs out of quests, then closes the map');
run("openAtlas('bag');atlasOpenJournal()");click('atlasQuestsClose');assert(!run('atlasOpen'));assert(run('bagOpen'),'Ordinary close retains inventory return');
console.log('PASS: current/selected area, tracked summary, separate quest browsing, saved tracking, gameplay return, popup, controls, completed quests, and compass spin/wiggle/glow settling.');
