import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run}=await loadEditorGame(process.cwd(),{log(){},warn(){},error:console.error},{furniture:false});
run(`mode='play';gameplayStarted=true;loadMap('house22');quest=Q.DONE;
foesHeld=false;devSafe=false;saintT=0;mounted=false;smithUpgrade=false;worn.ward=false;worn.twin=false;
houseLootTaken.clear();pHp=pMax=6;pInv=0;P.act=null;deadShown=false;
const soulwingItem=BAG.find(i=>i.key==='soulwing');`);
assert(!run('soulwingItem.has()'));
run(`IceMoth.defeated();houseLootTaken.add(IceMoth.rewardId);saveGame();`);
assert(run('IceMoth.defeatedAlready()&&soulwingItem.has()'));
assert(run("atlasQuestComplete('soulwing')"));
assert.equal(run('soulwingItem.icon()'),'inventory_soulwing');
assert(run('readSaveSlot(activeSaveSlot).houseLootTaken.includes(IceMoth.rewardId)'),'Collected reward is saved');
run(`const soulwingArena={id:444,x:P.x/16,y:P.y/16,r:6.3};arenaLock=soulwingArena;arenaT=1;
foes=[{kind:'plant1',hp:17,st:'walk',x:P.x+50,y:P.y,idx:91}];
const soulwingFoes=foes,soulwingEnemy=foes[0];gold=321;
const soulwingPlace=[MAPID,P.x,P.y];hurtPlayer(99);`);
assert(run('dying()'),'Fatal damage reaches the normal death animation');
run('stepAct(1);');
assert.equal(run('pHp'),6,'Revival restores full health');
assert.equal(run('pInv'),3,'A short protection window prevents instant repeat damage');
assert(!run('dying()||deadShown||soulwingItem.has()'),'No game over; relic consumed');
assert(run("atlasQuestComplete('soulwing')"),'Spending the relic does not undo collection');
assert(!run("atlasQuestOptions().some(q=>q.id==='soulwing')"),'The opened chest is not offered as an active quest again');
assert(run("atlasQuestStages({id:'soulwing'}).every(([,done])=>done)"),'Completed quest stages stay checked');
assert(run('arenaLock===soulwingArena&&foes===soulwingFoes&&foes[0]===soulwingEnemy'),'Battle state is retained');
assert.equal(run('foes[0].hp'),17,'Enemy damage is retained');
assert.equal(run('gold'),321,'No death penalty');
assert.equal(run('JSON.stringify([MAPID,P.x,P.y])'),run('JSON.stringify(soulwingPlace)'),'No teleport or map reload');
assert.equal(run('heal.kind'),'elixir','Revival displays the healing effect');
run('hurtPlayer(99);');assert.equal(run('pHp'),6,'Protection blocks follow-up hits');
assert(run('readSaveSlot(activeSaveSlot).houseLootTaken.includes(IceMoth.spentId)'),'Consumption is autosaved');
run('IceMoth.defeated();');assert(!run('IceMoth.owned()'),'Repeated victory callback cannot recharge it');
assert(run('loadGame(activeSaveSlot)'));assert(!run('soulwingItem.has()'),'Consumed state survives a real reload');
assert(run("atlasQuestComplete('soulwing')&&!atlasQuestOptions().some(q=>q.id==='soulwing')"),'Reload preserves completion after consumption');
run('foesHeld=false;pInv=0;pHp=1;P.act=null;deadShown=false;hurtPlayer(99);stepAct(1);');
assert(run('deadShown&&dying()'),'The next death uses the ordinary game-over flow');
// An old victory save gets one charge without needing to respawn the boss.
run(`houseLootTaken.clear();houseLootTaken.add('world:ice-moth:defeated');
const legacySoulwingSave=captureSave();delete legacySoulwingSave.bossRewardChests;
localStorage.setItem(saveKey(2),JSON.stringify(legacySoulwingSave));`);
assert(run('loadGame(2)&&soulwingItem.has()'));
run('pHp=0;P.act={kind:"die"};showDeath();');assert(!run('soulwingItem.has()'));
run('houseLootTaken.clear();saveToSlot(3,true);');
assert(run('loadGame(3)'));assert(!run('soulwingItem.has()'),'Fresh slots do not inherit another slot’s relic');
assert(!run("atlasQuestComplete('soulwing')"),'Collection belongs to its save slot');
run('IceMoth.defeated();');
assert(run("atlasQuestOptions().some(q=>q.id==='soulwing')&&!atlasQuestComplete('soulwing')"),'An unclaimed boss chest still creates the collection quest');
console.log('PASS: boss reward, real fatal-hit/death-animation revival, unchanged battle/position/gold, protection, one use, autosave/reload, old victories and save-slot isolation.');
