import assert from 'node:assert/strict';
import {loadEditorGame} from '../tools/editor-game-context.mjs';
const {run}=await loadEditorGame(process.cwd());
await run('loadPublishedEditorLayouts()');
run("loadMap('smithy');P.x=200;P.y=240;var smith=MD.roomActors.find(a=>a.spr==='smithy_anim_8'),bench=MD.roomActors.find(a=>a.editKey==='remaining:smithy:16'),forge=MD.roomActors.find(a=>a.exactFurniture&&a.n==='forge')");
const array=s=>Array.from(run(s));
assert(run('smith.workshopStation&&bench.workshopBase&&bench.editorLocked'));
assert.equal(run('smith.sy'),212,'Depth includes the full bench');
assert.deepEqual(array('MD.roomBlocks[smith.moveBlocks[0]]'),[182,176,221,212]);
assert.equal(run('bench.moveBlocks.length'),0,'Collision has exactly one owner');
assert(!run('canStand(200,208)'),'Corin cannot stand inside the bench front as in the screenshot');
assert(!run('canStand(200,218)'),'The whole feet box must clear the front');
assert(run('canStand(200,219)'),'Corin can still approach closely enough to speak');
run('while(canStand(P.x,P.y-1))P.y--');
assert.equal(run('P.y'),219,'Walking north stops at the visible station edge');
assert(run('Math.abs(P.y-npcs.find(n=>n.n==="Dunstan").talkY)<24'),'Dialogue remains reachable');
assert(run('pickEditorActor(200,207)===smith'),'Clicking the bench selects the complete station');
run('moveEditorActor(smith,232,208,true)');
assert.deepEqual(array('MD.roomBlocks[smith.moveBlocks[0]]'),[214,192,253,228]);
assert.deepEqual(array('[bench.x,bench.y]'),[233.5,228]);
assert(run('canStand(200,208)'),'No old collision is left behind');
assert(run('canStand(200,200)'),'The original tabletop collision also moves away');
assert(!run('canStand(232,224)'),'Collision moves with the station');
assert.equal(run('npcs.find(n=>n.n==="Dunstan").talkY'),225);
run("applyActorLayout(MD,'smithy')");
assert.deepEqual(array('MD.roomBlocks[smith.moveBlocks[0]]'),[214,192,253,228],'Saved moves do not drift');
run('moveEditorActor(forge,forge.x+16,forge.y+8,true)');
assert.deepEqual(array('[smith.x,smith.y,bench.x,bench.y]'),[248,216,249.5,236]);
assert.deepEqual(array('MD.roomBlocks[smith.moveBlocks[0]]'),[230,200,269,236],'Parent moves shift collision exactly once');
const count=run('MD.roomBlocks.length');run('prepareDunstanStation(MD)');
assert.equal(run('MD.roomBlocks.length'),count,'Preparing again is idempotent');
console.log('PASS: actual smithy station blocks Corin at its front edge, keeps dialogue reachable, and moves artwork/base/collision together without drift.');
